import {test,expect} from '@playwright/test';
import {PNG} from 'pngjs';
import {readFileSync,writeFileSync} from 'node:fs';
const tolerance=JSON.parse(readFileSync(new URL('../../migration/manifest.json',import.meta.url))).comparison;
test('Point Lights model matches the r186 scene with adapted material and supports controls',async({page},testInfo)=>{
  test.setTimeout(90000);
  await page.goto('/reference/three-js/point-lights.html');
  let canvas=page.locator('canvas');
  await expect(canvas).toHaveAttribute('data-ready','true',{timeout:30000});
  const reference=await canvas.screenshot();
  await page.goto('/web/?example=3&static=1');canvas=page.locator('canvas');
  await expect.poll(async()=>Number(await canvas.getAttribute('data-frames')),{timeout:30000}).toBeGreaterThan(2);
  expect(await canvas.getAttribute('data-error')).toBeNull();
  const actual=await canvas.screenshot();
  writeFileSync(testInfo.outputPath('reference.png'),reference);writeFileSync(testInfo.outputPath('rust.png'),actual);
  const a=PNG.sync.read(actual),b=PNG.sync.read(reference);
  expect([a.width,a.height]).toEqual([b.width,b.height]);
  let different=0;
  for(let i=0;i<a.data.length;i+=4)if([0,1,2].some(c=>Math.abs(a.data[i+c]-b.data[i+c])>tolerance.channel_tolerance))different++;
  expect(different/(a.width*a.height),`${different} differing pixels`).toBeLessThanOrEqual(tolerance.maximum_different_pixel_fraction);
  await page.locator('#deformation').fill('0');
  const frame=Number(await canvas.getAttribute('data-frames'));
  await expect.poll(async()=>Number(await canvas.getAttribute('data-frames'))).toBeGreaterThan(frame+1);
  expect((await canvas.screenshot()).equals(actual)).toBe(false);
  expect(await canvas.getAttribute('data-demo-time')).toBe('6');
  await page.getByRole('button',{name:'再生',exact:true}).click();
  await expect.poll(async()=>Number(await canvas.getAttribute('data-demo-time'))).toBeGreaterThan(6.1);
  await page.getByRole('button',{name:'一時停止',exact:true}).click();
  const paused=await canvas.getAttribute('data-demo-time');
  await page.waitForTimeout(200);expect(await canvas.getAttribute('data-demo-time')).toBe(paused);
  const beforeOrbit=await canvas.screenshot();
  const bounds=await canvas.boundingBox();
  await page.mouse.move(bounds.x+360,bounds.y+360);await page.mouse.down();
  await page.mouse.move(bounds.x+460,bounds.y+390,{steps:5});await page.mouse.up();
  await page.waitForTimeout(100);
  expect((await canvas.screenshot()).equals(beforeOrbit)).toBe(false);
  expect(await canvas.getAttribute('data-error')).toBeNull();
});
