// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// the cluster grid (16 × 16 tiles at 512 px) is set per size: NX_, NY_, NXY_.
// directives
// system
var<private> instanceIndex : u32;
// locals
// structs
// uniforms
@binding( 1 ) @group( 1 ) var nodeUniform1 : texture_2d<f32>;
@binding( 2 ) @group( 1 ) var nodeUniform3 : texture_2d<f32>;
struct lightIndexesStruct {
	value : array< vec4<i32> >
};
@binding( 0 ) @group( 1 )
var<storage, read_write> lightIndexes : lightIndexesStruct;
struct renderStruct {
	clusteredCameraNear : f32,
	clusteredCameraFar : f32,
	clusteredCameraViewMatrix : mat4x4<f32>,
	clusteredCameraProjectionMatrix : mat4x4<f32>
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
struct objectStruct {
	nodeUniform7 : u32
};
@binding( 3 ) @group( 1 )
var<uniform> object : objectStruct;
// vars
var<private> nodeVar0 : i32;
var<private> nodeVar1 : u32;
var<private> nodeVar2 : vec4<f32>;
var<private> nodeVar3 : i32;
var<private> nodeVar4 : vec4<f32>;
var<private> nodeVar5 : u32;
var<private> nodeVar6 : f32;
var<private> nodeVar7 : f32;
var<private> nodeVar8 : f32;
var<private> nodeVar9 : f32;
var<private> nodeVar10 : f32;
var<private> nodeVar11 : f32;
var<private> nodeVar12 : f32;
var<private> nodeVar13 : u32;
var<private> nodeVar14 : f32;
var<private> nodeVar15 : f32;
var<private> nodeVar16 : f32;
var<private> nodeVar17 : f32;
var<private> nodeVar18 : f32;
var<private> nodeVar19 : f32;
var<private> nodeVar20 : vec3<f32>;
// codes
@compute @workgroup_size( 64, 1, 1 )
fn main( @builtin( global_invocation_id ) globalId : vec3<u32>,
	@builtin( workgroup_id ) workgroupId : vec3<u32>,
	@builtin( local_invocation_id ) localId : vec3<u32>,
	@builtin( num_workgroups ) numWorkgroups : vec3<u32> ) {
	// local vars
	// system
	instanceIndex = globalId.x
		+ globalId.y * ( 64 * numWorkgroups.x )
		+ globalId.z * ( 64 * numWorkgroups.x ) * ( 1 * numWorkgroups.y );
	// flow
	// code
	// flow -> Update Clustered Lights
	if ( instanceIndex >= object.nodeUniform7 ) { return; }
	for ( var i : i32 = 0; i < 16; i ++ ) {
		lightIndexes.value[ ( ( instanceIndex * 16u ) + u32( i ) ) ] = vec4<i32>( 0, 0, 0, 0 );
	}
	nodeVar0 = 0;
	for ( var i : i32 = 0; i < 1024; i ++ ) {
		nodeVar1 = ( instanceIndex / NXY_u );
		nodeVar2 = textureLoad( nodeUniform1, vec2<i32>( i32( nodeVar1 ), i32( 0.0 ) ), u32( 0u ) );
		nodeVar3 = ( i32( nodeVar2.x ) + i );
		if ( ( ( nodeVar0 >= 64 ) || ( nodeVar3 >= i32( nodeVar2.y ) ) ) ) {
			return;
		}
		nodeVar4 = textureLoad( nodeUniform3, vec2<i32>( nodeVar3, i32( 0.0 ) ), u32( 0u ) );
		nodeVar5 = ( instanceIndex % NX_u );
		nodeVar6 = ( ( f32( nodeVar5 ) * X_STEP ) - 1.0 );
		nodeVar7 = ( render.clusteredCameraFar / render.clusteredCameraNear );
		nodeVar8 = ( - ( render.clusteredCameraNear * pow( nodeVar7, ( f32( nodeVar1 ) * 0.041666666666666664 ) ) ) );
		nodeVar9 = ( 1.0 / render.clusteredCameraProjectionMatrix[ 0u ][ 0u ] );
		nodeVar10 = ( ( - nodeVar8 ) * nodeVar9 );
		nodeVar11 = ( - ( render.clusteredCameraNear * pow( nodeVar7, ( f32( ( nodeVar1 + 1u ) ) * 0.041666666666666664 ) ) ) );
		nodeVar12 = ( ( - nodeVar11 ) * nodeVar9 );
		nodeVar13 = ( ( instanceIndex / NX_u ) % NY_u );
		nodeVar14 = ( 1.0 - ( f32( ( nodeVar13 + 1u ) ) * Y_STEP ) );
		nodeVar15 = ( 1.0 / render.clusteredCameraProjectionMatrix[ 1u ][ 1u ] );
		nodeVar16 = ( ( - nodeVar8 ) * nodeVar15 );
		nodeVar17 = ( ( - nodeVar11 ) * nodeVar15 );
		nodeVar18 = ( ( f32( ( nodeVar5 + 1u ) ) * X_STEP ) - 1.0 );
		nodeVar19 = ( 1.0 - ( f32( nodeVar13 ) * Y_STEP ) );
		nodeVar20 = ( ( render.clusteredCameraViewMatrix * vec4<f32>( nodeVar4.xyz, 1.0 ) ).xyz - max( vec3<f32>( min( ( nodeVar6 * nodeVar10 ), ( nodeVar6 * nodeVar12 ) ), min( ( nodeVar14 * nodeVar16 ), ( nodeVar14 * nodeVar17 ) ), nodeVar11 ), min( ( render.clusteredCameraViewMatrix * vec4<f32>( nodeVar4.xyz, 1.0 ) ).xyz, vec3<f32>( max( ( nodeVar18 * nodeVar10 ), ( nodeVar18 * nodeVar12 ) ), max( ( nodeVar19 * nodeVar16 ), ( nodeVar19 * nodeVar17 ) ), nodeVar8 ) ) ) );
		if ( ( dot( nodeVar20, nodeVar20 ) <= ( nodeVar4.w * nodeVar4.w ) ) ) {
			lightIndexes.value[ ( ( instanceIndex * 16u ) + u32( ( nodeVar0 / 4 ) ) ) ][ ( nodeVar0 % 4 ) ] = ( nodeVar3 + 1 );
			nodeVar0 = ( nodeVar0 + 1 );
		}
	}
}
