// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
@binding( 0 ) @group( 0 ) var nodeUniform0_sampler : sampler;
@binding( 1 ) @group( 0 ) var nodeUniform0 : texture_2d<f32>;
struct NodeBuffer_1076Struct {
	value : array< vec4<f32>, 6 >
};
@binding( 2 ) @group( 0 )
var<uniform> NodeBuffer_1076 : NodeBuffer_1076Struct;
struct objectStruct {
	nodeUniform2 : vec2<f32>
};
@binding( 3 ) @group( 0 )
var<uniform> object : objectStruct;
// vars
// codes
fn FxaaPixelShader ( uv : vec2<f32>, texSize : vec2<f32> ) -> vec4<f32> {
	var nodeVar0 : vec2<f32>;
	var nodeVar1 : vec4<f32>;
	var nodeVar2 : f32;
	var nodeVar3 : vec4<f32>;
	var nodeVar4 : f32;
	var nodeVar5 : vec4<f32>;
	var nodeVar6 : f32;
	var nodeVar7 : vec4<f32>;
	var nodeVar8 : f32;
	var nodeVar9 : vec4<f32>;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	var nodeVar14 : vec4<f32>;
	var nodeVar15 : f32;
	var nodeVar16 : vec4<f32>;
	var nodeVar17 : f32;
	var nodeVar18 : vec4<f32>;
	var nodeVar19 : f32;
	var nodeVar20 : vec4<f32>;
	var nodeVar21 : f32;
	var nodeVar22 : bool;
	var nodeVar23 : f32;
	var nodeVar24 : f32;
	var nodeVar25 : f32;
	var nodeVar26 : f32;
	var nodeVar27 : f32;
	var nodeVar28 : f32;
	var nodeVar29 : f32;
	var nodeVar30 : vec2<f32>;
	var nodeVar31 : vec2<f32>;
	var nodeVar32 : vec2<f32>;
	var nodeVar33 : vec4<f32>;
	var nodeVar34 : f32;
	var nodeVar35 : f32;
	var nodeVar36 : f32;
	var nodeVar37 : bool;
	var nodeVar38 : vec4<f32>;
	var nodeVar39 : vec2<f32>;
	var nodeVar40 : vec4<f32>;
	var nodeVar41 : f32;
	var nodeVar42 : bool;
	var nodeVar43 : vec4<f32>;
	var nodeVar44 : f32;
	var nodeVar45 : f32;
	var nodeVar46 : f32;
	var nodeVar47 : bool;
	var nodeVar48 : f32;
	var nodeVar49 : f32;
	var nodeVar50 : f32;
	var nodeVar51 : vec4<f32>;
	nodeVar0 = uv;
	nodeVar1 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( 0.0, 1.0 ) ) ), -100.0 );
	nodeVar2 = dot( nodeVar1.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
	nodeVar3 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( 1.0, 0.0 ) ) ), -100.0 );
	nodeVar4 = dot( nodeVar3.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
	nodeVar5 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( 0.0, -1.0 ) ) ), -100.0 );
	nodeVar6 = dot( nodeVar5.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
	nodeVar7 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( -1.0, 0.0 ) ) ), -100.0 );
	nodeVar8 = dot( nodeVar7.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
	nodeVar9 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, uv, -100.0 );
	nodeVar10 = dot( nodeVar9.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
	nodeVar11 = max( max( max( max( nodeVar2, nodeVar4 ), nodeVar6 ), nodeVar8 ), nodeVar10 );
	nodeVar12 = ( nodeVar11 - min( min( min( min( nodeVar2, nodeVar4 ), nodeVar6 ), nodeVar8 ), nodeVar10 ) );
	if ( ( ! ( nodeVar12 < max( 0.0312, ( 0.063 * nodeVar11 ) ) ) ) ) {
		nodeVar14 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( 1.0, 1.0 ) ) ), -100.0 );
		nodeVar15 = dot( nodeVar14.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
		nodeVar16 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( 1.0, -1.0 ) ) ), -100.0 );
		nodeVar17 = dot( nodeVar16.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
		nodeVar18 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( -1.0, 1.0 ) ) ), -100.0 );
		nodeVar19 = dot( nodeVar18.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
		nodeVar20 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, ( uv + ( texSize * vec2<f32>( -1.0, -1.0 ) ) ), -100.0 );
		nodeVar21 = dot( nodeVar20.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) );
		nodeVar22 = ( ( ( abs( ( ( nodeVar2 + nodeVar6 ) - ( nodeVar10 * 2.0 ) ) ) * 2.0 ) + ( abs( ( ( nodeVar15 + nodeVar17 ) - ( nodeVar4 * 2.0 ) ) ) + abs( ( ( nodeVar19 + nodeVar21 ) - ( nodeVar8 * 2.0 ) ) ) ) ) >= ( ( abs( ( ( nodeVar4 + nodeVar8 ) - ( nodeVar10 * 2.0 ) ) ) * 2.0 ) + ( abs( ( ( nodeVar15 + nodeVar19 ) - ( nodeVar2 * 2.0 ) ) ) + abs( ( ( nodeVar17 + nodeVar21 ) - ( nodeVar6 * 2.0 ) ) ) ) ) );
		if ( nodeVar22 ) {
			nodeVar13 = texSize.y;
		} else {
			nodeVar13 = texSize.x;
		}
		nodeVar23 = nodeVar13;
		nodeVar24 = 0.0;
		nodeVar25 = 0.0;
		if ( nodeVar22 ) {
			nodeVar26 = nodeVar2;
		} else {
			nodeVar26 = nodeVar4;
		}
		nodeVar27 = abs( ( nodeVar26 - nodeVar10 ) );
		if ( nodeVar22 ) {
			nodeVar28 = nodeVar6;
		} else {
			nodeVar28 = nodeVar8;
		}
		nodeVar29 = abs( ( nodeVar28 - nodeVar10 ) );
		if ( ( nodeVar27 < nodeVar29 ) ) {
			nodeVar23 = ( - nodeVar23 );
			nodeVar24 = nodeVar28;
			nodeVar25 = nodeVar29;
		} else {
			nodeVar24 = nodeVar26;
			nodeVar25 = nodeVar27;
		}
		nodeVar30 = uv;
		nodeVar31 = vec2<f32>( 0.0, 0.0 );
		if ( nodeVar22 ) {
			nodeVar30.y = ( nodeVar30.y + ( nodeVar23 * 0.5 ) );
			nodeVar31 = vec2<f32>( texSize.x, 0.0 );
		} else {
			nodeVar30.x = ( nodeVar30.x + ( nodeVar23 * 0.5 ) );
			nodeVar31 = vec2<f32>( 0.0, texSize.y );
		}
		nodeVar32 = ( nodeVar30 + ( nodeVar31 * vec2<f32>( NodeBuffer_1076.value[ 0u ].x ) ) );
		nodeVar33 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, nodeVar32, -100.0 );
		nodeVar34 = ( ( nodeVar10 + nodeVar24 ) * 0.5 );
		nodeVar35 = ( dot( nodeVar33.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) ) - nodeVar34 );
		nodeVar36 = ( nodeVar25 * 0.25 );
		nodeVar37 = ( abs( nodeVar35 ) >= nodeVar36 );
		for ( var i : i32 = 1; i < 6; i ++ ) {
			if ( nodeVar37 ) {
				break;
			}
			nodeVar32 = ( nodeVar32 + ( nodeVar31 * vec2<f32>( NodeBuffer_1076.value[ i ].x ) ) );
			nodeVar38 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, nodeVar32, -100.0 );
			nodeVar35 = ( dot( nodeVar38.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) ) - nodeVar34 );
			nodeVar37 = ( abs( nodeVar35 ) >= nodeVar36 );
		}
		if ( ( ! nodeVar37 ) ) {
			nodeVar32 = ( nodeVar32 + ( nodeVar31 * vec2<f32>( 8.0 ) ) );
		}
		nodeVar39 = ( nodeVar30 - ( nodeVar31 * vec2<f32>( NodeBuffer_1076.value[ 0u ].x ) ) );
		nodeVar40 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, nodeVar39, -100.0 );
		nodeVar41 = ( dot( nodeVar40.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) ) - nodeVar34 );
		nodeVar42 = ( abs( nodeVar41 ) >= nodeVar36 );
		for ( var i : i32 = 1; i < 6; i ++ ) {
			if ( nodeVar42 ) {
				break;
			}
			nodeVar39 = ( nodeVar39 - ( nodeVar31 * vec2<f32>( NodeBuffer_1076.value[ i ].x ) ) );
			nodeVar43 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, nodeVar39, -100.0 );
			nodeVar41 = ( dot( nodeVar43.xyz, vec3<f32>( 0.3, 0.59, 0.11 ) ) - nodeVar34 );
			nodeVar42 = ( abs( nodeVar41 ) >= nodeVar36 );
		}
		if ( ( ! nodeVar42 ) ) {
			nodeVar39 = ( nodeVar39 - ( nodeVar31 * vec2<f32>( 8.0 ) ) );
		}
		nodeVar44 = 0.0;
		nodeVar45 = 0.0;
		if ( nodeVar22 ) {
			nodeVar44 = ( nodeVar32.x - uv.x );
			nodeVar45 = ( uv.x - nodeVar39.x );
		} else {
			nodeVar44 = ( nodeVar32.y - uv.y );
			nodeVar45 = ( uv.y - nodeVar39.y );
		}
		nodeVar46 = 0.0;
		nodeVar47 = false;
		if ( ( nodeVar44 <= nodeVar45 ) ) {
			nodeVar46 = nodeVar44;
			nodeVar47 = ( nodeVar35 >= 0.0 );
		} else {
			nodeVar46 = nodeVar45;
			nodeVar47 = ( nodeVar41 >= 0.0 );
		}
		nodeVar48 = 0.0;
		if ( ( nodeVar47 == ( ( nodeVar10 - nodeVar34 ) >= 0.0 ) ) ) {
			nodeVar48 = 0.0;
		} else {
			nodeVar48 = ( 0.5 - ( nodeVar46 / ( nodeVar44 + nodeVar45 ) ) );
		}
		if ( nodeVar22 ) {
			nodeVar49 = smoothstep( 0.0, 1.0, clamp( ( abs( ( ( ( ( 2.0 * ( ( ( nodeVar2 + nodeVar4 ) + nodeVar6 ) + nodeVar8 ) ) + ( ( ( nodeVar15 + nodeVar19 ) + nodeVar17 ) + nodeVar21 ) ) * 0.08333333333333333 ) - nodeVar10 ) ) / max( nodeVar12, 0.0 ) ), 0.0, 1.0 ) );
			nodeVar0.y = ( nodeVar0.y + ( nodeVar23 * max( ( ( nodeVar49 * nodeVar49 ) * 1.0 ), nodeVar48 ) ) );
		} else {
			nodeVar50 = smoothstep( 0.0, 1.0, clamp( ( abs( ( ( ( ( 2.0 * ( ( ( nodeVar2 + nodeVar4 ) + nodeVar6 ) + nodeVar8 ) ) + ( ( ( nodeVar15 + nodeVar19 ) + nodeVar17 ) + nodeVar21 ) ) * 0.08333333333333333 ) - nodeVar10 ) ) / max( nodeVar12, 0.0 ) ), 0.0, 1.0 ) );
			nodeVar0.x = ( nodeVar0.x + ( nodeVar23 * max( ( ( nodeVar50 * nodeVar50 ) * 1.0 ), nodeVar48 ) ) );
		}
	}
	nodeVar51 = textureSampleBias( nodeUniform0, nodeUniform0_sampler, nodeVar0, -100.0 );
	return nodeVar51;
}
@fragment
fn main( @location( 0 ) nodeVarying0 : vec2<f32> ) -> OutputStruct {
	// flow
	// code
	// result
	output.color = FxaaPixelShader( nodeVarying0, object.nodeUniform2 );
	return output;
}
