// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// the cluster grid (16 × 16 tiles at 512 px) is set per size: NX_, NY_, NXY_.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
@binding( 0 ) @group( 1 ) var nodeUniform0_sampler : sampler;
@binding( 1 ) @group( 1 ) var nodeUniform0 : texture_2d<f32>;
struct lightIndexesStruct {
	value : array< vec4<i32> >
};
@binding( 3 ) @group( 1 )
var<storage, read> lightIndexes : lightIndexesStruct;
struct renderStruct {
	clusteredCameraNear : f32,
	clusteredCameraFar : f32,
	cameraProjectionMatrixInverse : mat4x4<f32>,
	nodeUniform8 : f32
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
struct objectStruct {
	nodeUniform4 : i32,
	nodeUniform5 : vec2<f32>,
	nodeUniform7 : f32
};
@binding( 2 ) @group( 1 )
var<uniform> object : objectStruct;
// vars
var<private> nodeVar0 : vec4<f32>;
var<private> nodeVar1 : vec4<f32>;
var<private> nodeVar2 : i32;
var<private> nodeVar3 : vec2<f32>;
var<private> nodeVar5 : vec4<f32>;
var<private> positionView : vec3<f32>;
var<private> nodeVar6 : i32;
var<private> nodeVar7 : i32;
var<private> nodeVar8 : vec2<f32>;
var<private> nodeVar9 : f32;
var<private> nodeVar10 : vec4<f32>;
var<private> nodeVar11 : vec4<f32>;
var<private> nodeVar12 : vec4<f32>;
// codes
fn fn1 ( color : vec4<f32> ) -> vec4<f32> {
	var nodeVar0 : vec4<f32>;
	if ( ( color.w == 0.0 ) ) {
		nodeVar0 = vec4<f32>( 0.0, 0.0, 0.0, 0.0 );
	} else {
		nodeVar0 = vec4<f32>( ( color.xyz / vec3<f32>( color.w ) ), color.w );
	}
	return nodeVar0;
}
fn neutralToneMapping ( color : vec3<f32>, exposure : f32 ) -> vec3<f32> {
	var nodeVar0 : vec3<f32>;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : f32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	nodeVar0 = ( color * vec3<f32>( exposure ) );
	nodeVar2 = min( nodeVar0.x, min( nodeVar0.y, nodeVar0.z ) );
	if ( ( nodeVar2 < 0.08 ) ) {
		nodeVar1 = ( nodeVar2 - ( 6.25 * ( nodeVar2 * nodeVar2 ) ) );
	} else {
		nodeVar1 = 0.04;
	}
	nodeVar0 = ( nodeVar0 - vec3<f32>( nodeVar1 ) );
	nodeVar3 = max( nodeVar0.x, max( nodeVar0.y, nodeVar0.z ) );
	if ( ( nodeVar3 < 0.76 ) ) {
		return nodeVar0;
	}
	nodeVar4 = ( 1.0 - 0.76 );
	nodeVar5 = ( 1.0 - ( ( nodeVar4 * nodeVar4 ) / ( nodeVar3 + ( nodeVar4 - 0.76 ) ) ) );
	nodeVar0 = ( nodeVar0 * vec3<f32>( ( nodeVar5 / nodeVar3 ) ) );
	return mix( nodeVar0, vec3<f32>( nodeVar5 ), ( 1.0 - ( 1.0 / ( ( 0.15 * ( nodeVar3 - nodeVar5 ) ) + 1.0 ) ) ) );
}
fn sRGBTransferOETF ( color : vec3<f32> ) -> vec3<f32> {
	return mix( ( ( pow( color, vec3<f32>( 0.41666 ) ) * vec3<f32>( 1.055 ) ) - vec3<f32>( 0.055 ) ), ( color * vec3<f32>( 12.92 ) ), vec3<f32>( ( color <= vec3<f32>( 0.0031308 ) ) ) );
}
fn fn0 ( color : vec4<f32> ) -> vec4<f32> {
	return vec4<f32>( ( color.xyz * vec3<f32>( color.w ) ), color.w );
}
@fragment
fn main( @location( 0 ) v_clipSpace : vec4<f32>,
	@location( 1 ) nodeVarying1 : vec2<f32>,
	@builtin( position ) fragCoord : vec4<f32> ) -> OutputStruct {
	// flow
	// code
	nodeVar0 = textureSample( nodeUniform0, nodeUniform0_sampler, nodeVarying1 );
	nodeVar1 = nodeVar0;
	nodeVar2 = 0;
	nodeVar3 = floor( ( fragCoord.xy / vec2<f32>( 32.0 ) ) );
	nodeVar5 = ( render.cameraProjectionMatrixInverse * v_clipSpace );
	positionView = ( nodeVar5.xyz / vec3<f32>( nodeVar5.w ) );
	nodeVar6 = ( ( i32( nodeVar3.x ) + ( i32( nodeVar3.y ) * NX_ ) ) + ( i32( clamp( floor( ( ( log( ( ( - positionView.z ) / render.clusteredCameraNear ) ) * ( 1.0 / log( ( render.clusteredCameraFar / render.clusteredCameraNear ) ) ) ) * 24.0 ) ), 0.0, 23.0 ) ) * NXY_ ) );
	nodeVar7 = nodeVar6;
	if ( ( object.nodeUniform4 >= 0 ) ) {
		nodeVar8 = floor( ( fragCoord.xy / vec2<f32>( f32( 32 ) ) ) );
		nodeVar7 = ( ( i32( nodeVar8.x ) + ( i32( nodeVar8.y ) * i32( object.nodeUniform5.x ) ) ) + ( object.nodeUniform4 * ( i32( object.nodeUniform5.x ) * i32( object.nodeUniform5.y ) ) ) );
	}
	for ( var i : i32 = 0; i < 64; i ++ ) {
		if ( ( lightIndexes.value[ ( ( nodeVar7 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] == 0 ) ) {
			break;
		}
		nodeVar2 = ( nodeVar2 + 1 );
	}
	nodeVar9 = ( f32( nodeVar2 ) / 64.0 );
	nodeVar10 = mix( nodeVar1, vec4<f32>( mix( mix( vec3<f32>( 0.0, 0.0, 1.0 ), vec3<f32>( 0.0, 1.0, 0.0 ), clamp( ( nodeVar9 * 2.0 ), 0.0, 1.0 ) ), vec3<f32>( 1.0, 0.0, 0.0 ), clamp( ( ( nodeVar9 - 0.5 ) * 2.0 ), 0.0, 1.0 ) ), 1.0 ), ( object.nodeUniform7 * step( 0.0001, nodeVar9 ) ) );
	nodeVar11 = fn1( vec4<f32>( nodeVar10.xyz, clamp( nodeVar10.w, 0.0, 1.0 ) ) );
	nodeVar12 = vec4<f32>( neutralToneMapping( nodeVar11.xyz, render.nodeUniform8 ), nodeVar11.w );
	// result
	output.color = fn0( vec4<f32>( sRGBTransferOETF( nodeVar12.xyz ), nodeVar12.w ) );
	return output;
}
