// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// directives
// structs
// uniforms
// varyings
struct VaryingsStruct {
	@location( 0 ) v_clipSpace : vec4<f32>,
	@location( 1 ) nodeVarying1 : vec2<f32>,
	@builtin( position ) builtinClipSpace : vec4<f32>
};
var<private> varyings : VaryingsStruct;
// vars
var<private> nodeVar4 : vec4<f32>;
// codes
@vertex
fn main( @builtin( vertex_index ) vertexIndex : u32,
	@location( 0 ) uv : vec2<f32> ) -> VaryingsStruct {
	// flow
	// code
	varyings.nodeVarying1 = uv;
	nodeVar4 = vec4<f32>( array< f32, 3 >( -1.0, -1.0, 3.0 )[ vertexIndex ], array< f32, 3 >( 3.0, -1.0, -1.0 )[ vertexIndex ], 0.0, 1.0 );
	varyings.v_clipSpace = nodeVar4;
	// result
	varyings.builtinClipSpace = nodeVar4;
	return varyings;
}
