// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// the cluster grid (16 × 16 tiles at 512 px) is set per size: NX_, NY_, NXY_.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
@binding( 2 ) @group( 1 ) var nodeUniform11 : texture_2d<f32>;
struct lightIndexesStruct {
	value : array< vec4<i32> >
};
@binding( 1 ) @group( 1 )
var<storage, read> lightIndexes : lightIndexesStruct;
struct objectStruct {
	nodeUniform0 : vec3<f32>,
	nodeUniform1 : f32,
	nodeUniform2 : f32,
	nodeUniform3 : vec3<f32>,
	nodeUniform4 : vec3<f32>,
	nodeUniform5 : f32,
	nodeUniform8 : mat4x4<f32>,
	nodeUniform13 : mat3x3<f32>
};
@binding( 0 ) @group( 1 )
var<uniform> object : objectStruct;
struct renderStruct {
	clusteredCameraNear : f32,
	clusteredCameraFar : f32,
	clusteredCameraViewMatrix : mat4x4<f32>,
	cameraProjectionMatrix : mat4x4<f32>,
	cameraViewMatrix : mat4x4<f32>
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
// vars
var<private> DiffuseColor : vec4<f32>;
var<private> Shininess : f32;
var<private> SpecularColor : vec3<f32>;
var<private> EmissiveColor : vec3<f32>;
var<private> Output : vec4<f32>;
var<private> directDiffuse : vec3<f32>;
var<private> directSpecular : vec3<f32>;
var<private> nodeVar0 : vec2<f32>;
var<private> nodeVar1 : i32;
var<private> nodeVar2 : vec4<f32>;
var<private> nodeVar3 : vec3<f32>;
var<private> normalViewGeometry : vec3<f32>;
var<private> NORMAL_normalView : vec3<f32>;
var<private> normalView : vec3<f32>;
var<private> nodeVar4 : vec3<f32>;
var<private> nodeVar5 : vec4<f32>;
var<private> nodeVar6 : f32;
var<private> nodeVar7 : f32;
var<private> nodeVar8 : f32;
var<private> nodeVar9 : f32;
var<private> nodeVar10 : vec3<f32>;
var<private> positionViewDirection : vec3<f32>;
var<private> nodeVar11 : vec3<f32>;
var<private> nodeVar12 : f32;
var<private> nodeVar13 : f32;
var<private> indirectDiffuse : vec3<f32>;
var<private> irradiance : vec3<f32>;
var<private> nodeVar14 : vec4<f32>;
var<private> nodeVar15 : vec4<f32>;
var<private> nodeVar16 : vec4<f32>;
var<private> ambientOcclusion : f32;
var<private> nodeVar17 : vec3<f32>;
var<private> totalDiffuse : vec3<f32>;
var<private> nodeVar18 : vec3<f32>;
var<private> totalSpecular : vec3<f32>;
var<private> indirectSpecular : vec3<f32>;
var<private> nodeVar19 : vec3<f32>;
var<private> outgoingLight : vec3<f32>;
var<private> nodeVar20 : vec3<f32>;
var<private> nodeVar21 : vec4<f32>;
var<private> normalLocal : vec3<f32>;
// codes
@fragment
fn main( @location( 0 ) v_positionView : vec3<f32>,
	@location( 1 ) v_positionViewDirection : vec3<f32>,
	@location( 2 ) v_normalViewGeometry : vec3<f32>,
	@location( 3 ) nodeVarying6 : vec3<f32>,
	@builtin( position ) fragCoord : vec4<f32> ) -> OutputStruct {
	// flow
	// code
	DiffuseColor = vec4<f32>( object.nodeUniform0, 1.0 );
	DiffuseColor.w = ( DiffuseColor.w * object.nodeUniform1 );
	DiffuseColor.w = 1.0;
	Shininess = max( object.nodeUniform2, 0.0001 );
	SpecularColor = object.nodeUniform3;
	EmissiveColor = ( object.nodeUniform4 * vec3<f32>( object.nodeUniform5 ) );
	directDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	directSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	for ( var i : i32 = 0; i < 64; i ++ ) {
		nodeVar0 = floor( ( fragCoord.xy / vec2<f32>( 32.0 ) ) );
		nodeVar1 = ( ( i32( nodeVar0.x ) + ( i32( nodeVar0.y ) * NX_ ) ) + ( i32( clamp( floor( ( ( log( ( ( - v_positionView.z ) / render.clusteredCameraNear ) ) * ( 1.0 / log( ( render.clusteredCameraFar / render.clusteredCameraNear ) ) ) ) * 24.0 ) ), 0.0, 23.0 ) ) * NXY_ ) );
		if ( ( lightIndexes.value[ ( ( nodeVar1 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] == 0 ) ) {
			break;
		}
		nodeVar2 = textureLoad( nodeUniform11, vec2<i32>( ( lightIndexes.value[ ( ( nodeVar1 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] - 1 ), i32( 0.0 ) ), u32( 0u ) );
		nodeVar3 = ( ( render.clusteredCameraViewMatrix * vec4<f32>( nodeVar2.xyz, 1.0 ) ).xyz - v_positionView );
		if ( ( ( nodeVar2.w == 0.0 ) || ( dot( nodeVar3, nodeVar3 ) <= ( nodeVar2.w * nodeVar2.w ) ) ) ) {
			normalViewGeometry = normalize( v_normalViewGeometry );
			NORMAL_normalView = normalViewGeometry;
			normalView = NORMAL_normalView;
			nodeVar4 = normalize( nodeVar3 );
			nodeVar5 = textureLoad( nodeUniform11, vec2<i32>( ( lightIndexes.value[ ( ( nodeVar1 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] - 1 ), i32( 1.0 ) ), u32( 0u ) );
			if ( ( nodeVar2.w > 0.0 ) ) {
				nodeVar7 = length( nodeVar3 );
				nodeVar8 = ( nodeVar7 / nodeVar2.w );
				nodeVar9 = clamp( ( 1.0 - ( ( ( nodeVar8 * nodeVar8 ) * nodeVar8 ) * nodeVar8 ) ), 0.0, 1.0 );
				nodeVar6 = ( ( 1.0 / max( pow( nodeVar7, nodeVar5.w ), 0.01 ) ) * ( nodeVar9 * nodeVar9 ) );
			} else {
				nodeVar6 = ( 1.0 / max( pow( length( nodeVar3 ), nodeVar5.w ), 0.01 ) );
			}
			nodeVar10 = ( vec3<f32>( clamp( dot( normalView, nodeVar4 ), 0.0, 1.0 ) ) * ( nodeVar5.xyz * vec3<f32>( nodeVar6 ) ) );
			directDiffuse = ( directDiffuse + ( nodeVar10 * ( DiffuseColor.xyz * vec3<f32>( 0.3183098861837907 ) ) ) );
			positionViewDirection = normalize( v_positionViewDirection );
			nodeVar11 = normalize( ( nodeVar4 + positionViewDirection ) );
			nodeVar12 = clamp( dot( positionViewDirection, nodeVar11 ), 0.0, 1.0 );
			nodeVar13 = exp2( ( ( ( nodeVar12 * -5.55473 ) - 6.98316 ) * nodeVar12 ) );
			directSpecular = ( directSpecular + ( ( nodeVar10 * ( ( ( ( SpecularColor * vec3<f32>( ( 1.0 - nodeVar13 ) ) ) + vec3<f32>( ( 1.0 * nodeVar13 ) ) ) * vec3<f32>( 0.25 ) ) * vec3<f32>( ( ( ( ( Shininess * 0.5 ) + 1.0 ) * 0.3183098861837907 ) * pow( clamp( dot( normalView, nodeVar11 ), 0.0, 1.0 ), Shininess ) ) ) ) ) * vec3<f32>( 1.0 ) ) );
		}
	}
	indirectDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	irradiance = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar14 = ( DiffuseColor * vec4<f32>( 0.3183098861837907 ) );
	nodeVar15 = ( vec4<f32>( irradiance, 1.0 ) * nodeVar14 );
	nodeVar16 = ( vec4<f32>( indirectDiffuse, 1.0 ) + nodeVar15 );
	indirectDiffuse = nodeVar16.xyz;
	ambientOcclusion = 1.0;
	nodeVar17 = ( indirectDiffuse * vec3<f32>( ambientOcclusion ) );
	indirectDiffuse = nodeVar17;
	nodeVar18 = ( directDiffuse + indirectDiffuse );
	totalDiffuse = nodeVar18;
	indirectSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar19 = ( directSpecular + indirectSpecular );
	totalSpecular = nodeVar19;
	nodeVar20 = ( totalDiffuse + totalSpecular );
	outgoingLight = nodeVar20;
	nodeVar21 = max( vec4<f32>( ( outgoingLight + EmissiveColor ), DiffuseColor.w ), vec4<f32>( 0.0 ) );
	Output = nodeVar21;
	normalLocal = nodeVarying6;
	// result
	output.color = nodeVar21;
	return output;
}
