// Generated by three.js r186 (Node System) for webgpu_lights_clustered.
// the cluster grid (16 × 16 tiles at 512 px) is set per size: NX_, NY_, NXY_.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
@binding( 2 ) @group( 1 ) var nodeUniform8 : texture_2d<f32>;
struct lightIndexesStruct {
	value : array< vec4<i32> >
};
@binding( 1 ) @group( 1 )
var<storage, read> lightIndexes : lightIndexesStruct;
struct objectStruct {
	nodeUniform2 : f32,
	nodeUniform5 : mat4x4<f32>
};
@binding( 0 ) @group( 1 )
var<uniform> object : objectStruct;
struct renderStruct {
	clusteredCameraNear : f32,
	clusteredCameraFar : f32,
	clusteredCameraViewMatrix : mat4x4<f32>,
	cameraProjectionMatrix : mat4x4<f32>,
	cameraViewMatrix : mat4x4<f32>
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
// vars
var<private> DiffuseColor : vec4<f32>;
var<private> Output : vec4<f32>;
var<private> directDiffuse : vec3<f32>;
var<private> directSpecular : vec3<f32>;
var<private> nodeVar0 : vec2<f32>;
var<private> nodeVar1 : i32;
var<private> nodeVar2 : vec4<f32>;
var<private> nodeVar3 : vec3<f32>;
var<private> indirectDiffuse : vec3<f32>;
var<private> nodeVar4 : vec4<f32>;
var<private> ambientOcclusion : f32;
var<private> nodeVar5 : vec3<f32>;
var<private> nodeVar6 : vec3<f32>;
var<private> totalDiffuse : vec3<f32>;
var<private> nodeVar7 : vec3<f32>;
var<private> totalSpecular : vec3<f32>;
var<private> indirectSpecular : vec3<f32>;
var<private> nodeVar8 : vec3<f32>;
var<private> outgoingLight : vec3<f32>;
var<private> nodeVar9 : vec3<f32>;
var<private> nodeVar10 : vec4<f32>;
// codes
@fragment
fn main( @location( 0 ) v_positionView : vec3<f32>,
	@location( 1 ) nodeVarying4 : vec3<f32>,
	@builtin( position ) fragCoord : vec4<f32> ) -> OutputStruct {
	// flow
	// code
	DiffuseColor = vec4<f32>( nodeVarying4, 1.0 );
	DiffuseColor.w = ( DiffuseColor.w * object.nodeUniform2 );
	DiffuseColor.w = 1.0;
	directDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	directSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	for ( var i : i32 = 0; i < 64; i ++ ) {
		nodeVar0 = floor( ( fragCoord.xy / vec2<f32>( 32.0 ) ) );
		nodeVar1 = ( ( i32( nodeVar0.x ) + ( i32( nodeVar0.y ) * NX_ ) ) + ( i32( clamp( floor( ( ( log( ( ( - v_positionView.z ) / render.clusteredCameraNear ) ) * ( 1.0 / log( ( render.clusteredCameraFar / render.clusteredCameraNear ) ) ) ) * 24.0 ) ), 0.0, 23.0 ) ) * NXY_ ) );
		if ( ( lightIndexes.value[ ( ( nodeVar1 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] == 0 ) ) {
			break;
		}
		nodeVar2 = textureLoad( nodeUniform8, vec2<i32>( ( lightIndexes.value[ ( ( nodeVar1 * 16 ) + ( i / 4 ) ) ][ ( i % 4 ) ] - 1 ), i32( 0.0 ) ), u32( 0u ) );
		nodeVar3 = ( ( render.clusteredCameraViewMatrix * vec4<f32>( nodeVar2.xyz, 1.0 ) ).xyz - v_positionView );
		if ( ( ( nodeVar2.w == 0.0 ) || ( dot( nodeVar3, nodeVar3 ) <= ( nodeVar2.w * nodeVar2.w ) ) ) ) {
		}
	}
	indirectDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	indirectDiffuse = vec4<f32>( 0.0, 0.0, 0.0, 0.0 ).xyz;
	nodeVar4 = ( vec4<f32>( indirectDiffuse, 1.0 ) + vec4<f32>( 1.0, 1.0, 1.0, 0.0 ) );
	indirectDiffuse = nodeVar4.xyz;
	ambientOcclusion = 1.0;
	nodeVar5 = ( indirectDiffuse * vec3<f32>( ambientOcclusion ) );
	indirectDiffuse = nodeVar5;
	nodeVar6 = ( indirectDiffuse * DiffuseColor.xyz );
	indirectDiffuse = nodeVar6;
	nodeVar7 = ( directDiffuse + indirectDiffuse );
	totalDiffuse = nodeVar7;
	indirectSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar8 = ( directSpecular + indirectSpecular );
	totalSpecular = nodeVar8;
	nodeVar9 = ( totalDiffuse + totalSpecular );
	outgoingLight = nodeVar9;
	nodeVar10 = max( vec4<f32>( outgoingLight, DiffuseColor.w ), vec4<f32>( 0.0 ) );
	Output = nodeVar10;
	// result
	output.color = nodeVar10;
	return output;
}
