//! The uniforms and bindings of the material shaders r186 generates for
//! webgpu_vxgi_sponza, per struct member: what each holds, as the
//! reference page's draws show ( tools/vxgi_sponza tables, regenerated with
//! the captured WGSL ).
use super::{Role, V};

pub(super) const SHADOW: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    (
        "objectStruct",
        "nodeUniform1",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform2", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform5", V::Model),
];
pub(super) const SHADOW_TEXTURES: &[(&str, Role)] = &[("nodeUniform0", Role::Map)];
pub(super) const SHADOW_MASKED: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    (
        "objectStruct",
        "nodeUniform1",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform2", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform3", V::AlphaTest),
    ("objectStruct", "nodeUniform6", V::Model),
];
pub(super) const SHADOW_MASKED_TEXTURES: &[(&str, Role)] = &[("nodeUniform0", Role::Map)];
pub(super) const PREPASS_TEXTURED: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform32", V::PreviousProjection),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform21", V::LightColor),
    ("renderStruct", "nodeUniform29", V::Ambient),
    ("renderStruct", "nodeUniform19", V::LightPosition),
    ("renderStruct", "nodeUniform20", V::LightTarget),
    ("renderStruct", "nodeUniform22", V::ShadowMatrix),
    ("renderStruct", "nodeUniform23", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform24", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform26", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform27", V::Const(&[2048.0, 2048.0])),
    ("renderStruct", "nodeUniform28", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform6",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform7", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform8",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform10", V::NormalMatrix),
    ("objectStruct", "nodeUniform11", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform12", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform14", V::Model),
    (
        "objectStruct",
        "nodeUniform16",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform17", V::NormalScale),
    ("objectStruct", "nodeUniform30", V::Unjittered),
    ("objectStruct", "nodeUniform31", V::Model),
    ("objectStruct", "nodeUniform33", V::PreviousView),
    ("objectStruct", "nodeUniform34", V::Model),
];
pub(super) const PREPASS_TEXTURED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform5", Role::RoughnessMetalness),
    ("nodeUniform13", Role::Dfg),
    ("nodeUniform15", Role::NormalMap),
    ("nodeUniform25", Role::Shadow),
];
pub(super) const PREPASS_MASKED: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform33", V::PreviousProjection),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform22", V::LightColor),
    ("renderStruct", "nodeUniform30", V::Ambient),
    ("renderStruct", "nodeUniform20", V::LightPosition),
    ("renderStruct", "nodeUniform21", V::LightTarget),
    ("renderStruct", "nodeUniform23", V::ShadowMatrix),
    ("renderStruct", "nodeUniform24", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform25", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform29", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform27", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform28", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::AlphaTest),
    ("objectStruct", "nodeUniform5", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform7",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform8", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform9",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform11", V::NormalMatrix),
    ("objectStruct", "nodeUniform12", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform13", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform15", V::Model),
    (
        "objectStruct",
        "nodeUniform17",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform18", V::NormalScale),
    ("objectStruct", "nodeUniform31", V::Unjittered),
    ("objectStruct", "nodeUniform32", V::Model),
    ("objectStruct", "nodeUniform34", V::PreviousView),
    ("objectStruct", "nodeUniform35", V::Model),
];
pub(super) const PREPASS_MASKED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform6", Role::RoughnessMetalness),
    ("nodeUniform14", Role::Dfg),
    ("nodeUniform16", Role::NormalMap),
    ("nodeUniform26", Role::Shadow),
];
pub(super) const PREPASS_BASE: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform26", V::PreviousProjection),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform15", V::LightColor),
    ("renderStruct", "nodeUniform23", V::Ambient),
    ("renderStruct", "nodeUniform13", V::LightPosition),
    ("renderStruct", "nodeUniform14", V::LightTarget),
    ("renderStruct", "nodeUniform16", V::ShadowMatrix),
    ("renderStruct", "nodeUniform17", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform18", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform22", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform20", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform21", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[0.0])),
    ("objectStruct", "nodeUniform5", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform7", V::NormalMatrix),
    ("objectStruct", "nodeUniform8", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform9", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform11", V::Model),
    ("objectStruct", "nodeUniform24", V::Unjittered),
    ("objectStruct", "nodeUniform25", V::Model),
    ("objectStruct", "nodeUniform27", V::PreviousView),
    ("objectStruct", "nodeUniform28", V::Model),
];
pub(super) const PREPASS_BASE_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform10", Role::Dfg),
    ("nodeUniform19", Role::Shadow),
];
pub(super) const PREPASS_SKY: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform7", V::Time),
    ("renderStruct", "nodeUniform16", V::PreviousProjection),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "cameraPosition", V::CameraPosition),
    ("objectStruct", "nodeUniform0", V::Model),
    ("objectStruct", "nodeUniform2", V::Const(&[0.8])),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform5", V::Const(&[0.5])),
    ("objectStruct", "nodeUniform6", V::Const(&[0.0002])),
    ("objectStruct", "nodeUniform8", V::Const(&[2e-05])),
    ("objectStruct", "nodeUniform9", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform10", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform12", V::NormalMatrix),
    ("objectStruct", "nodeUniform13", V::Unjittered),
    ("objectStruct", "nodeUniform15", V::Model),
    ("objectStruct", "nodeUniform17", V::PreviousView),
    ("objectStruct", "nodeUniform18", V::Model),
    ("objectStruct", "nodeUniform19", V::SunDirection),
    ("objectStruct", "nodeUniform20", V::Const(&[2.0])),
    ("objectStruct", "nodeUniform21", V::Const(&[10.0])),
    ("objectStruct", "nodeUniform22", V::Const(&[0.005])),
];
pub(super) const PREPASS_SKY_TEXTURES: &[(&str, Role)] = &[];
pub(super) const SCENE_TEXTURED: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform23", V::LightColor),
    ("renderStruct", "nodeUniform31", V::Ambient),
    ("renderStruct", "nodeUniform21", V::LightPosition),
    ("renderStruct", "nodeUniform22", V::LightTarget),
    ("renderStruct", "nodeUniform24", V::ShadowMatrix),
    ("renderStruct", "nodeUniform25", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform26", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform30", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform5", V::Size),
    ("renderStruct", "nodeUniform28", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform29", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform6", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform8",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform9", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform10",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform12", V::NormalMatrix),
    ("objectStruct", "nodeUniform13", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform14", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform16", V::Model),
    (
        "objectStruct",
        "nodeUniform18",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform19", V::NormalScale),
];
pub(super) const SCENE_TEXTURED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform4", Role::Ao),
    ("nodeUniform7", Role::RoughnessMetalness),
    ("nodeUniform15", Role::Dfg),
    ("nodeUniform17", Role::NormalMap),
    ("nodeUniform27", Role::Shadow),
    ("nodeUniform32", Role::Gi),
];
pub(super) const SCENE_MASKED: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform24", V::LightColor),
    ("renderStruct", "nodeUniform32", V::Ambient),
    ("renderStruct", "nodeUniform22", V::LightPosition),
    ("renderStruct", "nodeUniform23", V::LightTarget),
    ("renderStruct", "nodeUniform25", V::ShadowMatrix),
    ("renderStruct", "nodeUniform26", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform27", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform31", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform6", V::Size),
    ("renderStruct", "nodeUniform29", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform30", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::AlphaTest),
    ("objectStruct", "nodeUniform7", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform9",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform10", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform11",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform13", V::NormalMatrix),
    ("objectStruct", "nodeUniform14", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform15", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform17", V::Model),
    (
        "objectStruct",
        "nodeUniform19",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform20", V::NormalScale),
];
pub(super) const SCENE_MASKED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform5", Role::Ao),
    ("nodeUniform8", Role::RoughnessMetalness),
    ("nodeUniform16", Role::Dfg),
    ("nodeUniform18", Role::NormalMap),
    ("nodeUniform28", Role::Shadow),
    ("nodeUniform33", Role::Gi),
];
pub(super) const SCENE_BASE: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform17", V::LightColor),
    ("renderStruct", "nodeUniform25", V::Ambient),
    ("renderStruct", "nodeUniform15", V::LightPosition),
    ("renderStruct", "nodeUniform16", V::LightTarget),
    ("renderStruct", "nodeUniform18", V::ShadowMatrix),
    ("renderStruct", "nodeUniform19", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform20", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform24", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform5", V::Size),
    ("renderStruct", "nodeUniform22", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform23", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform6", V::Const(&[0.0])),
    ("objectStruct", "nodeUniform7", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform9", V::NormalMatrix),
    ("objectStruct", "nodeUniform10", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform11", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform13", V::Model),
];
pub(super) const SCENE_BASE_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform4", Role::Ao),
    ("nodeUniform12", Role::Dfg),
    ("nodeUniform21", Role::Shadow),
    ("nodeUniform26", Role::Gi),
];
pub(super) const SCENE_SKY: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform7", V::Time),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "cameraPosition", V::CameraPosition),
    ("renderStruct", "nodeUniform12", V::Size),
    ("objectStruct", "nodeUniform0", V::Model),
    ("objectStruct", "nodeUniform2", V::Const(&[0.8])),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform5", V::Const(&[0.5])),
    ("objectStruct", "nodeUniform6", V::Const(&[0.0002])),
    ("objectStruct", "nodeUniform8", V::Const(&[2e-05])),
    ("objectStruct", "nodeUniform9", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform10", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform13", V::SunDirection),
    ("objectStruct", "nodeUniform14", V::Const(&[2.0])),
    ("objectStruct", "nodeUniform15", V::Const(&[10.0])),
    ("objectStruct", "nodeUniform16", V::Const(&[0.005])),
];
pub(super) const SCENE_SKY_TEXTURES: &[(&str, Role)] = &[("nodeUniform11", Role::Ao)];
pub(super) const DIRECT_TEXTURED: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform21", V::LightColor),
    ("renderStruct", "nodeUniform29", V::Ambient),
    ("renderStruct", "nodeUniform19", V::LightPosition),
    ("renderStruct", "nodeUniform20", V::LightTarget),
    ("renderStruct", "nodeUniform22", V::ShadowMatrix),
    ("renderStruct", "nodeUniform23", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform24", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform28", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform26", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform27", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform6",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform7", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform8",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform10", V::NormalMatrix),
    ("objectStruct", "nodeUniform11", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform12", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform14", V::Model),
    (
        "objectStruct",
        "nodeUniform16",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform17", V::NormalScale),
];
pub(super) const DIRECT_TEXTURED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform5", Role::RoughnessMetalness),
    ("nodeUniform13", Role::Dfg),
    ("nodeUniform15", Role::NormalMap),
    ("nodeUniform25", Role::Shadow),
];
pub(super) const DIRECT_MASKED: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform22", V::LightColor),
    ("renderStruct", "nodeUniform30", V::Ambient),
    ("renderStruct", "nodeUniform20", V::LightPosition),
    ("renderStruct", "nodeUniform21", V::LightTarget),
    ("renderStruct", "nodeUniform23", V::ShadowMatrix),
    ("renderStruct", "nodeUniform24", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform25", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform29", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform27", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform28", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::AlphaTest),
    ("objectStruct", "nodeUniform5", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform7",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform8", V::Const(&[1.0])),
    (
        "objectStruct",
        "nodeUniform9",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform11", V::NormalMatrix),
    ("objectStruct", "nodeUniform12", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform13", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform15", V::Model),
    (
        "objectStruct",
        "nodeUniform17",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform18", V::NormalScale),
];
pub(super) const DIRECT_MASKED_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform6", Role::RoughnessMetalness),
    ("nodeUniform14", Role::Dfg),
    ("nodeUniform16", Role::NormalMap),
    ("nodeUniform26", Role::Shadow),
];
pub(super) const DIRECT_BASE: &[(&str, &str, V)] = &[
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "nodeUniform15", V::LightColor),
    ("renderStruct", "nodeUniform23", V::Ambient),
    ("renderStruct", "nodeUniform13", V::LightPosition),
    ("renderStruct", "nodeUniform14", V::LightTarget),
    ("renderStruct", "nodeUniform16", V::ShadowMatrix),
    ("renderStruct", "nodeUniform17", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform18", V::Const(&[0.0])),
    ("renderStruct", "nodeUniform22", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform20", V::Const(&[1.0])),
    ("renderStruct", "nodeUniform21", V::Const(&[2048.0, 2048.0])),
    ("objectStruct", "nodeUniform0", V::Color),
    (
        "objectStruct",
        "nodeUniform2",
        V::Const(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]),
    ),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[0.0])),
    ("objectStruct", "nodeUniform5", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform7", V::NormalMatrix),
    ("objectStruct", "nodeUniform8", V::Const(&[0.0, 0.0, 0.0])),
    ("objectStruct", "nodeUniform9", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform11", V::Model),
];
pub(super) const DIRECT_BASE_TEXTURES: &[(&str, Role)] = &[
    ("nodeUniform1", Role::Map),
    ("nodeUniform10", Role::Dfg),
    ("nodeUniform19", Role::Shadow),
];
pub(super) const DIRECT_SKY: &[(&str, &str, V)] = &[
    ("renderStruct", "nodeUniform7", V::Time),
    ("renderStruct", "cameraProjectionMatrix", V::Projection),
    ("renderStruct", "cameraViewMatrix", V::View),
    ("renderStruct", "cameraPosition", V::CameraPosition),
    ("objectStruct", "nodeUniform0", V::Model),
    ("objectStruct", "nodeUniform2", V::Const(&[0.8])),
    ("objectStruct", "nodeUniform3", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform4", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform5", V::Const(&[0.5])),
    ("objectStruct", "nodeUniform6", V::Const(&[0.0002])),
    ("objectStruct", "nodeUniform8", V::Const(&[2e-05])),
    ("objectStruct", "nodeUniform9", V::Const(&[0.4])),
    ("objectStruct", "nodeUniform10", V::Const(&[1.0])),
    ("objectStruct", "nodeUniform11", V::SunDirection),
    ("objectStruct", "nodeUniform12", V::Const(&[2.0])),
    ("objectStruct", "nodeUniform13", V::Const(&[10.0])),
    ("objectStruct", "nodeUniform14", V::Const(&[0.005])),
];
pub(super) const DIRECT_SKY_TEXTURES: &[(&str, Role)] = &[];
