//! Voxel painting, triangle picking, clipping intersection, scissored scene
//! comparison and custom blending from the pinned WebGL examples.
use super::gltf_viewer::{decode_texture_image, fetch};
use super::interactive_objects::Orbit;
use crate::tsl::Node;
use crate::{
    Error, Result,
    attribute::BufferAttribute,
    camera::*,
    geometry::*,
    material::*,
    math::*,
    raycast::Raycaster,
    renderer::*,
    scene::*,
    shader::ShaderProgram,
    tsl::{self, *},
};
use std::f64::consts::FRAC_PI_2;
use std::sync::Arc;
use wasm_bindgen::JsCast;
fn random(seed: &mut u32) -> f64 {
    *seed = seed.wrapping_mul(1664525).wrapping_add(1013904223);
    *seed as f64 / 4294967296.
}
fn call(name: &str, source: &str, args: &[Type], out: Type, nodes: &[Node]) -> Result<Node> {
    Ok(WgslFn::new(name, source, args, out)?.call(nodes))
}
fn positions(data: Vec<f32>) -> Result<Attribute> {
    Ok(Attribute::F32(BufferAttribute::new(data, 3, false)?))
}
/// `Color.setHSL`, returning sRGB components.
fn hsl(h: f64, s: f64, l: f64) -> [f64; 3] {
    let hue = |p: f64, q: f64, t: f64| {
        let t = t.rem_euclid(1.);
        if t < 1. / 6. {
            p + (q - p) * 6. * t
        } else if t < 0.5 {
            q
        } else if t < 2. / 3. {
            p + (q - p) * 6. * (2. / 3. - t)
        } else {
            p
        }
    };
    let q = if l <= 0.5 {
        l * (1. + s)
    } else {
        l + s - l * s
    };
    let p = 2. * l - q;
    let h = h.rem_euclid(1.);
    [hue(p, q, h + 1. / 3.), hue(p, q, h), hue(p, q, h - 1. / 3.)]
}
/// `GridHelper( size, divisions )` with its default colors.
fn grid_helper(size: f64, divisions: u32) -> Result<Line> {
    let (center, step, half) = (divisions / 2, size / divisions as f64, size / 2.);
    let (mut vertices, mut colors) = (vec![], vec![]);
    let mut k = -half;
    for i in 0..=divisions {
        vertices.extend([-half, 0., k, half, 0., k, k, 0., -half, k, 0., half].map(|v| v as f32));
        let c = Color::from_hex(if i == center { 0x444444 } else { 0x888888 }).0;
        for _ in 0..4 {
            colors.extend(c.to_array().map(|v| v as f32));
        }
        k += step;
    }
    let mut g = BufferGeometry::default();
    g.set_attribute("position", positions(vertices)?);
    g.set_attribute("color", positions(colors)?);
    let mut m = LineBasicMaterial::default();
    m.properties.vertex_colors = true;
    Ok(Line {
        geometry: Arc::new(g),
        material: Arc::new(Material::Line(m)),
        segments: true,
    })
}
/// `PlaneHelper( plane, 2, hex )`: an outline strip and a translucent one-sided quad.
fn plane_helper(s: &mut Scene, parent: Object3D, hex: u32) -> Result<Object3D> {
    let mut g = BufferGeometry::default();
    g.set_attribute(
        "position",
        positions(vec![
            1., -1., 0., -1., 1., 0., -1., -1., 0., 1., 1., 0., -1., 1., 0., -1., -1., 0., 1., -1.,
            0., 1., 1., 0.,
        ])?,
    );
    let mut m = LineBasicMaterial::default();
    m.properties.color = Color::from_hex(hex);
    let h = s.insert(NodeKind::Line(Line {
        geometry: Arc::new(g),
        material: Arc::new(Material::Line(m)),
        segments: false,
    }));
    let mut g = BufferGeometry::default();
    g.set_attribute(
        "position",
        positions(vec![
            1., 1., 0., -1., 1., 0., -1., -1., 0., 1., 1., 0., -1., -1., 0., 1., -1., 0.,
        ])?,
    );
    let mut m = MeshBasicMaterial::default();
    m.properties.color = Color::from_hex(hex);
    m.properties.opacity = 0.2;
    m.properties.transparent = true;
    m.properties.depth_write = false;
    let quad = s.insert(NodeKind::Mesh(Mesh::new(
        Arc::new(g),
        Arc::new(Material::Basic(m)),
    )));
    s.add(h, quad)?;
    s.add(parent, h)?;
    Ok(h)
}
/// Label canvas as generated by the original `generateLabelMaterial`.
fn label(text: &str, background: &str) -> Result<crate::material::Texture> {
    let fail = |e: wasm_bindgen::JsValue| Error::Asset(format!("label canvas: {e:?}"));
    let canvas = web_sys::OffscreenCanvas::new(128, 32).map_err(fail)?;
    let context = canvas
        .get_context("2d")
        .map_err(fail)?
        .ok_or(Error::Invalid("label context"))?
        .dyn_into::<web_sys::OffscreenCanvasRenderingContext2d>()
        .map_err(|e| fail(e.into()))?;
    context.set_fill_style_str(background);
    context.fill_rect(0., 0., 128., 32.);
    context.set_fill_style_str("white");
    context.set_font("bold 11pt arial");
    context.fill_text(text, 8., 22.).map_err(fail)?;
    let data = context
        .get_image_data(0., 0., 128., 32.)
        .map_err(fail)?
        .data()
        .to_vec();
    let mut t = crate::material::Texture::from_rgba(128, 32, data, true)?;
    t.mipmap_filter = Some(Filter::Linear);
    Ok(t)
}
/// Unlit textured material whose display (sRGB) output feeds fixed-function blending.
async fn blend_material(r: &Renderer, t: &GpuTexture) -> Result<ShaderMaterial> {
    let tex = tsl::Texture::External(0).sample(vec2(uv().x(), float(1.) - uv().y()));
    let rgb = call(
        "blend_encode",
        "fn blend_encode(c:vec3<f32>)->vec3<f32>{return srgb_output(c);}",
        &[Type::Vec3],
        Type::Vec3,
        &[tex.clone().rgb()],
    )?;
    let mut m = NodeMaterial::new(vec4(rgb, tex.swizzle("w")))
        .build(r, &[(&t.view, &t.sampler)])
        .await?;
    m.properties.transparent = true;
    Ok(m)
}
const SRC: [wgpu::BlendFactor; 11] = {
    use wgpu::BlendFactor as F;
    [
        F::Zero,
        F::One,
        F::Src,
        F::OneMinusSrc,
        F::SrcAlpha,
        F::OneMinusSrcAlpha,
        F::DstAlpha,
        F::OneMinusDstAlpha,
        F::Dst,
        F::OneMinusDst,
        F::SrcAlphaSaturated,
    ]
};
const SRC_NAMES: [&str; 11] = [
    "Zero",
    "One",
    "SrcColor",
    "OneMinusSrcColor",
    "SrcAlpha",
    "OneMinusSrcAlpha",
    "DstAlpha",
    "OneMinusDstAlpha",
    "DstColor",
    "OneMinusDstColor",
    "SrcAlphaSaturate",
];
/// CustomBlending: the alpha channel reuses the color factors and equation. WebGPU
/// requires One factors for min/max, which GL ignores for those equations.
fn custom_blend(
    src: wgpu::BlendFactor,
    dst: wgpu::BlendFactor,
    equation: usize,
) -> wgpu::BlendState {
    use wgpu::{BlendFactor as F, BlendOperation as O};
    let operation = [O::Add, O::Subtract, O::ReverseSubtract, O::Min, O::Max][equation];
    let (src_factor, dst_factor) = if equation >= 3 {
        (F::One, F::One)
    } else {
        (src, dst)
    };
    let c = wgpu::BlendComponent {
        src_factor,
        dst_factor,
        operation,
    };
    wgpu::BlendState { color: c, alpha: c }
}
const FULLSCREEN: &str = "fn project_vertex(surface:VertexOut,position:vec3<f32>)->VertexOut{var out=surface;out.clip=vec4(position.xy*2.0,1.0,1.0);return out;}";
struct Comparison {
    scene: Scene,
    camera: Object3D,
    output: Option<RenderTarget>,
    slider: f64,
}
pub(super) struct Demo {
    id: u32,
    time: f64,
    pointer: Vector2,
    shift: bool,
    orbit: Orbit,
    objects: Vec<Object3D>,
    rollover: Option<Object3D>,
    voxel: Option<(Arc<BufferGeometry>, Arc<Material>)>,
    line: Option<Object3D>,
    planes: Vec<Plane>,
    helpers: Option<Object3D>,
    params: [f32; 4],
    equation: usize,
    dirty: bool,
    comparison: Option<Comparison>,
    blends: Vec<(Object3D, wgpu::BlendFactor, wgpu::BlendFactor)>,
    background: Option<Object3D>,
}
impl Demo {
    pub async fn create(s: &mut Scene, c: Object3D, id: u32, r: &Renderer) -> Result<Self> {
        let aspect = match s.camera(c)?.0 {
            Camera::Perspective(p) => p.aspect,
            _ => 1.,
        };
        let (fov, near, far, position) = match id {
            193 => (45., 1., 10000., Vector3::new(500., 800., 1300.)),
            194 => (27., 1., 3500., Vector3::new(0., 0., 2750.)),
            195 => (40., 1., 200., Vector3::new(-1.5, 2.5, 3.)),
            196 => (35., 0.1, 100., Vector3::new(0., 0., 6.)),
            _ => (80., 1., 1000., Vector3::new(0., 0., 700.)),
        };
        s.get_mut(c)?.kind = NodeKind::Camera(Camera::Perspective(PerspectiveCamera {
            fov,
            near,
            far,
            aspect,
            ..Default::default()
        }));
        s.get_mut(c)?.position = position;
        s.look_at(c, Vector3::ZERO)?;
        s.background = Color::BLACK;
        let mut d = Self {
            id,
            time: 0.,
            pointer: Vector2::ZERO,
            shift: false,
            orbit: if id == 195 {
                Orbit::new(position, false, 1., (1., 10.))
            } else {
                Orbit::new(position, false, 1., (0., f64::INFINITY))
            },
            objects: vec![],
            rollover: None,
            voxel: None,
            line: None,
            planes: vec![
                Plane {
                    normal: Vector3::X,
                    constant: 0.,
                },
                Plane {
                    normal: Vector3::NEG_Y,
                    constant: 0.,
                },
                Plane {
                    normal: Vector3::NEG_Z,
                    constant: 0.,
                },
            ],
            helpers: None,
            params: [1., 1., 0., 0.],
            equation: 0,
            dirty: false,
            comparison: None,
            blends: vec![],
            background: None,
        };
        let mut seed = 186;
        match id {
            193 => {
                s.background = Color::from_hex(0xf0f0f0);
                let mut m = MeshBasicMaterial::default();
                m.properties.color = Color::from_hex(0xff0000);
                m.properties.opacity = 0.5;
                m.properties.transparent = true;
                let box50 = Arc::new(BoxGeometry::build(50., 50., 50.)?);
                d.rollover = Some(s.insert(NodeKind::Mesh(Mesh::new(
                    box50.clone(),
                    Arc::new(Material::Basic(m)),
                ))));
                let mut map = decode_texture_image(
                    &fetch("/web/gallery/assets/square-outline-textured.png").await?,
                )
                .await?;
                map.srgb = true;
                map.mipmap_filter = Some(Filter::Linear);
                let mut m = MeshLambertMaterial::default();
                m.properties.color = Color::from_hex(0xfeb74c);
                m.properties.map = Some(Arc::new(map));
                d.voxel = Some((box50, Arc::new(Material::Lambert(m))));
                s.insert(NodeKind::Line(grid_helper(1000., 20)?));
                let mut g = PlaneGeometry::build(1000., 1000., 1, 1)?;
                g.rotate_x(-FRAC_PI_2)?;
                let mut m = MeshBasicMaterial::default();
                m.properties.visible = false;
                d.objects.push(s.insert(NodeKind::Mesh(Mesh::new(
                    Arc::new(g),
                    Arc::new(Material::Basic(m)),
                ))));
                s.insert(NodeKind::Light(Light::Ambient {
                    color: Color::from_hex(0x606060),
                    intensity: 3.,
                }));
                let light = s.insert(NodeKind::Light(Light::Directional {
                    color: Color::WHITE,
                    intensity: 3.,
                    target: Vector3::ZERO,
                }));
                s.get_mut(light)?.position = Vector3::new(1., 0.75, 0.5).normalize();
            }
            194 => {
                s.background = Color::from_hex(0x050505);
                s.fog = Some(Fog::Linear {
                    color: Color::from_hex(0x050505),
                    near: 2000.,
                    far: 3500.,
                });
                s.insert(NodeKind::Light(Light::Ambient {
                    color: Color::from_hex(0x444444),
                    intensity: 3.,
                }));
                for (p, intensity) in [(Vector3::ONE, 1.5), (Vector3::NEG_Y, 4.5)] {
                    let light = s.insert(NodeKind::Light(Light::Directional {
                        color: Color::WHITE,
                        intensity,
                        target: Vector3::ZERO,
                    }));
                    s.get_mut(light)?.position = p;
                }
                let (n, d2) = (800., 120.);
                let (mut p, mut normals, mut colors) = (vec![], vec![], vec![]);
                for _ in 0..5000 {
                    let [x, y, z] = [0; 3].map(|_| random(&mut seed) * n - n / 2.);
                    let v: [Vector3; 3] = std::array::from_fn(|_| {
                        Vector3::new(
                            x + random(&mut seed) * d2 - d2 / 2.,
                            y + random(&mut seed) * d2 - d2 / 2.,
                            z + random(&mut seed) * d2 - d2 / 2.,
                        )
                    });
                    // The normal uses the f64 values; positions are then stored as Float32.
                    let normal = (v[2] - v[1]).cross(v[0] - v[1]).normalize();
                    let color = Vector3::new(x / n + 0.5, y / n + 0.5, z / n + 0.5);
                    for vertex in v {
                        p.extend(vertex.to_array().map(|x| x as f32));
                        normals.extend(normal.to_array().map(|x| x as f32));
                        colors.extend(color.to_array().map(|x| x as f32));
                    }
                }
                let mut g = BufferGeometry::default();
                g.set_attribute("position", positions(p)?);
                g.set_attribute("normal", positions(normals)?);
                g.set_attribute("color", positions(colors)?);
                let mut m = MeshPhongMaterial::default();
                m.properties.color = Color::from_hex(0xaaaaaa);
                m.specular = Color::WHITE;
                m.shininess = 250.;
                m.properties.side = Side::Double;
                m.properties.vertex_colors = true;
                d.objects.push(s.insert(NodeKind::Mesh(Mesh::new(
                    Arc::new(g),
                    Arc::new(Material::Phong(m)),
                ))));
                let mut g = BufferGeometry::default();
                g.set_attribute("position", positions(vec![0.; 12])?);
                let mut m = LineBasicMaterial::default();
                m.properties.transparent = true;
                let line = s.insert(NodeKind::Line(Line {
                    geometry: Arc::new(g),
                    material: Arc::new(Material::Line(m)),
                    segments: false,
                }));
                s.get_mut(line)?.visible = false;
                s.get_mut(line)?.frustum_culled = false;
                d.line = Some(line);
            }
            195 => {
                let light = s.insert(NodeKind::Light(Light::Hemisphere {
                    sky: Color::WHITE,
                    ground: Color::from_hex(0x080808),
                    intensity: 4.5,
                }));
                s.get_mut(light)?.position = Vector3::new(-1.25, 1., 1.25);
                for i in (1..=30).step_by(2) {
                    let rgb = hsl(random(&mut seed), 0.5, 0.5);
                    let mut m = MeshPhongMaterial::default();
                    m.properties.color = Color::from_srgb(rgb[0], rgb[1], rgb[2]);
                    m.properties.side = Side::Double;
                    m.properties.clipping_planes = d.planes.clone();
                    m.properties.clip_intersection = true;
                    m.properties.alpha_to_coverage = true;
                    d.objects.push(s.insert(NodeKind::Mesh(Mesh::new(
                        Arc::new(SphereGeometry::build(i as f64 / 30., 48, 24)?),
                        Arc::new(Material::Phong(m)),
                    ))));
                }
                let helpers = s.insert(NodeKind::Group);
                for hex in [0xff0000, 0x00ff00, 0x0000ff] {
                    plane_helper(s, helpers, hex)?;
                }
                s.get_mut(helpers)?.visible = false;
                d.helpers = Some(helpers);
                d.place_helpers(s)?;
            }
            196 => {
                s.background = Color::from_hex(0xbcd48f);
                let geometry = Arc::new(IcosahedronGeometry::build(1., 3)?);
                let mut right = Scene::new();
                right.background = Color::from_hex(0x8fbcd4);
                let camera = right.insert(NodeKind::Camera(s.camera(c)?.0.clone()));
                for (scene, wireframe) in [(&mut *s, false), (&mut right, true)] {
                    let light = scene.insert(NodeKind::Light(Light::Hemisphere {
                        sky: Color::WHITE,
                        ground: Color::from_hex(0x444444),
                        intensity: 3.,
                    }));
                    scene.get_mut(light)?.position = Vector3::new(-2., 2., 2.);
                    let mut m = MeshStandardMaterial::default();
                    m.properties.wireframe = wireframe;
                    scene.insert(NodeKind::Mesh(Mesh::new(
                        geometry.clone(),
                        Arc::new(Material::Standard(m)),
                    )));
                }
                // The scissored clear becomes a background quad inside the right scissor.
                let graph = NodeMaterial::new(vec4(uniform(0, Type::Vec3), float(1.)));
                let mut m = ShaderMaterial::new(Arc::new(
                    ShaderProgram::with_projection(r, &graph.wgsl(0)?, &[], &[], FULLSCREEN)
                        .await?,
                ));
                m.uniforms[0] = right.background.0.as_vec3().extend(1.).to_array();
                m.properties.depth_test = false;
                m.properties.depth_write = false;
                // One fullscreen triangle: (-1,-1), (3,-1), (-1,3) after FULLSCREEN's ×2.
                let mut g = BufferGeometry::default();
                g.set_attribute(
                    "position",
                    positions(vec![-0.5, -0.5, 0., 1.5, -0.5, 0., -0.5, 1.5, 0.])?,
                );
                g.set_attribute(
                    "uv",
                    Attribute::F32(BufferAttribute::new(vec![0.; 6], 2, false)?),
                );
                g.set_attribute(
                    "normal",
                    positions(vec![0., 0., 1., 0., 0., 1., 0., 0., 1.])?,
                );
                let quad = right.insert(NodeKind::Mesh(Mesh::new(
                    Arc::new(g),
                    Arc::new(Material::Shader(m)),
                )));
                right.get_mut(quad)?.frustum_culled = false;
                right.get_mut(quad)?.render_order = -10000;
                let slider = web_sys::window()
                    .and_then(|w| w.inner_width().ok())
                    .and_then(|w| w.as_f64())
                    .unwrap_or(512.)
                    / 2.;
                d.comparison = Some(Comparison {
                    scene: right,
                    camera,
                    output: None,
                    slider,
                });
            }
            _ => d.blending(s, r).await?,
        }
        if [193, 194, 195, 196].contains(&id) {
            d.orbit.apply(s, c)?;
        }
        Ok(d)
    }
    async fn blending(&mut self, s: &mut Scene, r: &Renderer) -> Result<()> {
        let mut t = decode_texture_image(
            &fetch(
                "/web/gallery/assets/environment-materials/textures/lensflare/lensflare0_alpha.png",
            )
            .await?,
        )
        .await?;
        t.srgb = true;
        t.mipmap_filter = Some(Filter::Linear);
        let texture = r.upload_texture(&Arc::new(t))?;
        let base = blend_material(r, &texture).await?;
        let (g1, g2) = (
            Arc::new(PlaneGeometry::build(100., 100., 1, 1)?),
            Arc::new(PlaneGeometry::build(100., 25., 1, 1)?),
        );
        // The destination list is the source list without SrcAlphaSaturate.
        for (i, &dst) in SRC[..10].iter().enumerate() {
            for (j, &src) in SRC.iter().enumerate() {
                let mut m = base.clone();
                m.properties.blending = Some(custom_blend(src, dst, 0));
                let h = s.insert(NodeKind::Mesh(Mesh::new(
                    g1.clone(),
                    Arc::new(Material::Shader(m)),
                )));
                let y = (i as f64 - 5.) * 110. + 50.;
                s.get_mut(h)?.position = Vector3::new((j as f64 - 5.5) * 110., -y, 0.);
                self.blends.push((h, src, dst));
            }
        }
        for (names, color, horizontal) in [
            (&SRC_NAMES[..], "rgba( 0, 150, 0, 1 )", true),
            (&SRC_NAMES[..10], "rgba( 150, 0, 0, 1 )", false),
        ] {
            for (k, name) in names.iter().enumerate() {
                let t = r.upload_texture(&Arc::new(label(name, color)?))?;
                let m = blend_material(r, &t).await?;
                let h = s.insert(NodeKind::Mesh(Mesh::new(
                    g2.clone(),
                    Arc::new(Material::Shader(m)),
                )));
                s.get_mut(h)?.position = if horizontal {
                    Vector3::new((k as f64 - 5.5) * 110., -(-500. - 70.), 0.)
                } else {
                    let y = (k as f64 - 5.) * 110. + 165.;
                    Vector3::new(-5.5 * 110. - 125., -(y - 120.), 0.)
                };
            }
        }
        // The same checker background as webgl_materials_blending, repeat (64, 32).
        let mut rgba = vec![];
        for y in 0..128 {
            for x in 0..128 {
                let v = if x < 64 && y < 64 {
                    if x >= 32 && y >= 32 { 0x99 } else { 0x55 }
                } else if x >= 64 && y >= 64 {
                    if x >= 96 && y >= 96 { 0x77 } else { 0x55 }
                } else {
                    0xdd
                };
                rgba.extend([v, v, v, 255]);
            }
        }
        let mut t = crate::material::Texture::from_rgba(128, 128, rgba, true)?;
        t.wrap_s = Wrapping::Repeat;
        t.wrap_t = Wrapping::Repeat;
        t.mipmap_filter = Some(Filter::Linear);
        let t = r.upload_texture(&Arc::new(t))?;
        let coordinate = vec2(
            uv().x() * float(64.) - uniform(0, Type::Float) * float(0.16),
            (float(1.) - uv().y()) * float(32.) + uniform(0, Type::Float) * float(0.08),
        );
        let color = call(
            "blend_background",
            "fn blend_background(c:vec4<f32>)->vec4<f32>{return vec4(srgb_output(c.rgb),c.a);}",
            &[Type::Vec4],
            Type::Vec4,
            &[tsl::Texture::External(0).sample(coordinate)],
        )?;
        let graph = NodeMaterial::new(color);
        let mut m = ShaderMaterial::new(Arc::new(
            ShaderProgram::with_projection(
                r,
                &graph.wgsl(1)?,
                &[],
                &[(&t.view, &t.sampler)],
                FULLSCREEN,
            )
            .await?,
        ));
        m.properties.depth_write = false;
        m.properties.depth_test = false;
        let h = s.insert(NodeKind::Mesh(Mesh::new(
            Arc::new(PlaneGeometry::build(1., 1., 1, 1)?),
            Arc::new(Material::Shader(m)),
        )));
        s.get_mut(h)?.frustum_culled = false;
        s.get_mut(h)?.render_order = -10000;
        self.background = Some(h);
        Ok(())
    }
    /// `PlaneHelper.updateMatrixWorld`: lookAt( normal ), then translateZ( -constant ).
    fn place_helpers(&self, s: &mut Scene) -> Result<()> {
        let Some(group) = self.helpers else {
            return Ok(());
        };
        let children = s.get(group)?.children().to_vec();
        for (h, plane) in children.into_iter().zip(&self.planes) {
            let n = s.get_mut(h)?;
            n.position = Vector3::ZERO;
            n.scale = Vector3::new(1., 1., 1.);
            s.look_at(h, plane.normal)?;
            let n = s.get_mut(h)?;
            n.translate_on_axis(Vector3::Z, -plane.constant);
        }
        Ok(())
    }
    fn raycast(&self, s: &Scene, c: Object3D) -> Result<Option<crate::raycast::Intersection>> {
        let (camera, world) = s.camera(c)?;
        let mut ray = Raycaster::default();
        ray.set_from_camera(self.pointer, camera, world)?;
        Ok(ray
            .intersect_objects(s, &self.objects, false)?
            .into_iter()
            .next())
    }
    /// Three.js `intersect.face.normal`: the local, unflipped triangle normal.
    fn face_normal(s: &Scene, hit: &crate::raycast::Intersection) -> Result<Vector3> {
        let g = s
            .get(hit.object)?
            .geometry()
            .ok_or(Error::Invalid("hit geometry"))?
            .clone();
        let p = g.positions()?;
        let f = hit.face_index.ok_or(Error::Invalid("hit face"))? * 3;
        let [a, b, c] = [f, f + 1, f + 2].map(|i| g.vertex_index(i).map(|i| p[i]));
        let (a, b, c) = (a?, b?, c?);
        Ok((c - b).cross(a - b).normalize())
    }
    fn snap(s: &Scene, hit: &crate::raycast::Intersection) -> Result<Vector3> {
        let p = hit.point + Self::face_normal(s, hit)?;
        Ok((p / 50.).floor() * 50. + Vector3::splat(25.))
    }
    pub fn update(&mut self, _s: &mut Scene, _c: Object3D, dt: f64, animate: bool) -> Result<()> {
        if animate {
            self.time += dt;
        }
        Ok(())
    }
    pub fn prepare(&mut self, s: &mut Scene, c: Object3D) -> Result<()> {
        let t = self.time;
        self.apply_parameters(s)?;
        if [195, 196].contains(&self.id) {
            self.orbit.apply(s, c)?;
        }
        match self.id {
            194 => {
                let mesh = self.objects[0];
                s.get_mut(mesh)?.quaternion = Euler {
                    angles: Vector3::new(t * 0.15, t * 0.25, 0.),
                    order: EulerOrder::XYZ,
                }
                .quaternion();
                s.update()?;
                let line = self.line.ok_or(Error::Invalid("line"))?;
                if let Some(hit) = self.raycast(s, c)? {
                    let g = s
                        .get(mesh)?
                        .geometry()
                        .ok_or(Error::Invalid("mesh"))?
                        .clone();
                    let p = g.positions()?;
                    let f = hit.face_index.ok_or(Error::Invalid("hit face"))? * 3;
                    // copyAt( a, b, c, a ), then applyMatrix4( mesh.matrix ) on the line.
                    let matrix = s.get(mesh)?.matrix_world;
                    let mut data = vec![];
                    for i in [f, f + 1, f + 2, f] {
                        let v = p[i].as_vec3().as_dvec3();
                        data.extend(matrix.transform_point3(v).to_array().map(|x| x as f32));
                    }
                    let n = s.get_mut(line)?;
                    if let NodeKind::Line(l) = &mut n.kind {
                        Arc::make_mut(&mut l.geometry).set_attribute("position", positions(data)?);
                    }
                    n.visible = true;
                } else {
                    s.get_mut(line)?.visible = false;
                }
            }
            196 => {
                let (camera, world) = s.camera(c)?;
                let (camera, node) = (camera.clone(), s.get(c)?.clone());
                let _ = world;
                if let Some(cmp) = &mut self.comparison {
                    let n = cmp.scene.get_mut(cmp.camera)?;
                    n.kind = NodeKind::Camera(camera);
                    n.position = node.position;
                    n.quaternion = node.quaternion;
                }
            }
            197 => {
                if let Some(h) = self.background
                    && let NodeKind::Mesh(m) = &mut s.get_mut(h)?.kind
                    && let Material::Shader(m) = Arc::make_mut(&mut m.materials[0])
                {
                    m.uniforms[0][0] = t as f32;
                }
            }
            _ => {}
        }
        Ok(())
    }
    /// Scissored rendering of the two comparison scenes into a shared target.
    pub fn render(
        &mut self,
        r: &Renderer,
        s: &mut Scene,
        c: Object3D,
        out: &RenderTarget,
    ) -> Result<bool> {
        let Some(cmp) = &mut self.comparison else {
            return Ok(false);
        };
        if cmp.output.as_ref().is_none_or(|t| {
            t.width != out.width
                || t.height != out.height
                || t.options.samples != out.options.samples
        }) {
            let mut options = out.options.clone();
            options.store_multisampled_color_buffer = true;
            cmp.output = Some(RenderTarget::with_options(
                &r.device, out.width, out.height, options,
            )?);
        }
        let target = cmp.output.as_mut().expect("comparison target");
        let dpr = web_sys::window()
            .map(|w| w.device_pixel_ratio())
            .unwrap_or(1.);
        let split = ((cmp.slider * dpr).round() as u32).min(out.width);
        target.set_load_color(false);
        target.scissor = Some([0, 0, split.max(1), out.height]);
        r.render(s, c, target)?;
        if split < out.width {
            target.set_load_color(true);
            target.scissor = Some([split, 0, out.width - split, out.height]);
            r.render(&mut cmp.scene, cmp.camera, target)?;
        }
        target.scissor = None;
        Ok(true)
    }
    pub fn output(&self) -> Option<&RenderTarget> {
        self.comparison.as_ref().and_then(|c| c.output.as_ref())
    }
    pub fn gpu_pointer(&mut self, s: &mut Scene, c: Object3D, x: f64, y: f64) -> Result<bool> {
        self.pointer = Vector2::new(x, y);
        if self.id != 193 {
            return Ok(false);
        }
        s.update()?;
        if let Some(hit) = self.raycast(s, c)? {
            let p = Self::snap(s, &hit)?;
            s.get_mut(self.rollover.ok_or(Error::Invalid("rollover"))?)?
                .position = p;
            return Ok(true);
        }
        Ok(false)
    }
    pub fn select(&mut self, s: &mut Scene, c: Object3D, x: f64, y: f64) -> Result<()> {
        if self.id != 193 {
            return Ok(());
        }
        self.pointer = Vector2::new(x, y);
        s.update()?;
        let Some(hit) = self.raycast(s, c)? else {
            return Ok(());
        };
        if self.shift {
            if hit.object != self.objects[0] {
                self.objects.retain(|h| *h != hit.object);
                s.dispose(hit.object)?;
            }
        } else {
            let p = Self::snap(s, &hit)?;
            let (g, m) = self.voxel.clone().ok_or(Error::Invalid("voxel"))?;
            let h = s.insert(NodeKind::Mesh(Mesh::new(g, m)));
            s.get_mut(h)?.position = p;
            self.objects.push(h);
        }
        Ok(())
    }
    pub fn key(&mut self, code: u32, down: bool) {
        if code == 16 {
            self.shift = down;
        }
    }
    pub fn slider(&mut self, x: f64) {
        if let Some(c) = &mut self.comparison {
            c.slider = x;
        }
    }
    #[allow(clippy::too_many_arguments)]
    pub fn input(
        &mut self,
        s: &Scene,
        c: Object3D,
        dx: f64,
        dy: f64,
        wheel: f64,
        pan: bool,
        height: f64,
    ) -> Result<()> {
        if ![195, 196].contains(&self.id) {
            return Ok(());
        }
        if pan {
            if self.id == 195 {
                return Ok(());
            }
            let Camera::Perspective(p) = s.camera(c)?.0 else {
                return Ok(());
            };
            self.orbit.pan(s.get(c)?, p.fov, dx, dy, height);
        } else if wheel != 0. {
            self.orbit.dolly(wheel);
        } else {
            self.orbit.rotate(dx, dy, height);
        }
        // The controls' pointer and wheel handlers call update() themselves.
        self.orbit.update();
        Ok(())
    }
    pub fn parameter(&mut self, index: usize, value: f32) -> Result<()> {
        match (self.id, index) {
            (195, 0..=3) if value.is_finite() => self.params[index] = value,
            (197, 0) if (0. ..=4.).contains(&value) => self.equation = value as usize,
            _ => return Err(Error::Invalid("interactive scene parameter")),
        }
        self.dirty = true;
        Ok(())
    }
    fn apply_parameters(&mut self, s: &mut Scene) -> Result<()> {
        if !std::mem::take(&mut self.dirty) {
            return Ok(());
        }
        if self.id == 197 {
            for &(h, src, dst) in &self.blends {
                if let NodeKind::Mesh(m) = &mut s.get_mut(h)?.kind {
                    Arc::make_mut(&mut m.materials[0]).properties_mut().blending =
                        Some(custom_blend(src, dst, self.equation));
                }
            }
            return Ok(());
        }
        for p in &mut self.planes {
            p.constant = self.params[2] as f64;
        }
        for &h in &self.objects {
            if let NodeKind::Mesh(m) = &mut s.get_mut(h)?.kind {
                let p = Arc::make_mut(&mut m.materials[0]).properties_mut();
                p.alpha_to_coverage = self.params[0] != 0.;
                p.clip_intersection = self.params[1] != 0.;
                p.clipping_planes = self.planes.clone();
            }
        }
        if let Some(h) = self.helpers {
            s.get_mut(h)?.visible = self.params[3] != 0.;
        }
        self.place_helpers(s)
    }
    pub fn seek(&mut self, t: f64) {
        self.time = t;
    }
}
