// Generated by three.js r186 (Node System) for webgpu_tsl_vfx_linkedparticles.
// directives
// structs
// uniforms
struct renderStruct {
	cameraProjectionMatrix : mat4x4<f32>,
	cameraViewMatrix : mat4x4<f32>
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
struct objectStruct {
	nodeUniform0 : vec3<f32>,
	nodeUniform4 : mat4x4<f32>
};
@binding( 0 ) @group( 1 )
var<uniform> object : objectStruct;
// varyings
struct VaryingsStruct {
	@location( 0 ) v_positionView : vec3<f32>,
	@location( 1 ) nodeVarying4 : vec4<f32>,
	@location( 2 ) nodeVarying5 : vec4<f32>,
	@builtin( position ) builtinClipSpace : vec4<f32>
};
var<private> varyings : VaryingsStruct;
// vars
var<private> modelViewMatrix : mat4x4<f32>;
var<private> VERTEX_nodeVar7 : vec4<f32>;
var<private> v_modelViewProjection : vec4<f32>;
var<private> positionLocal : vec3<f32>;
var<private> VERTEX_v_modelViewProjection : vec4<f32>;
// codes
@vertex
fn main( @location( 0 ) color : vec4<f32>,
	@location( 1 ) position : vec4<f32>,
	@location( 2 ) nodeAttribute1 : vec4<f32> ) -> VaryingsStruct {
	// flow
	// code
	varyings.nodeVarying4 = color;
	varyings.nodeVarying5 = nodeAttribute1;
	modelViewMatrix = ( render.cameraViewMatrix * object.nodeUniform4 );
	positionLocal = position.xyz;
	varyings.v_positionView = ( modelViewMatrix * vec4<f32>( positionLocal, 1.0 ) ).xyz;
	VERTEX_nodeVar7 = ( render.cameraProjectionMatrix * vec4<f32>( varyings.v_positionView, 1.0 ) );
	VERTEX_v_modelViewProjection = VERTEX_nodeVar7;
	// result
	varyings.builtinClipSpace = VERTEX_v_modelViewProjection;
	return varyings;
}
