// Generated by three.js r186 (Node System) for webgpu_tsl_vfx_linkedparticles.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
struct objectStruct {
	nodeUniform0 : vec3<f32>,
	nodeUniform4 : mat4x4<f32>
};
@binding( 0 ) @group( 1 )
var<uniform> object : objectStruct;
// vars
var<private> DiffuseColor : vec4<f32>;
var<private> Output : vec4<f32>;
var<private> indirectDiffuse : vec3<f32>;
var<private> nodeVar0 : vec4<f32>;
var<private> ambientOcclusion : f32;
var<private> nodeVar1 : vec3<f32>;
var<private> nodeVar2 : vec3<f32>;
var<private> totalDiffuse : vec3<f32>;
var<private> directDiffuse : vec3<f32>;
var<private> nodeVar3 : vec3<f32>;
var<private> totalSpecular : vec3<f32>;
var<private> directSpecular : vec3<f32>;
var<private> indirectSpecular : vec3<f32>;
var<private> nodeVar4 : vec3<f32>;
var<private> outgoingLight : vec3<f32>;
var<private> nodeVar5 : vec3<f32>;
var<private> nodeVar6 : vec4<f32>;
// codes
@fragment
fn main( @location( 0 ) v_positionView : vec3<f32>,
	@location( 1 ) nodeVarying4 : vec4<f32>,
	@location( 2 ) nodeVarying5 : vec4<f32> ) -> OutputStruct {
	// flow
	// code
	DiffuseColor = ( vec4<f32>( object.nodeUniform0, 1.0 ) * nodeVarying4 );
	DiffuseColor.w = ( DiffuseColor.w * nodeVarying5.w );
	indirectDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	indirectDiffuse = vec4<f32>( 0.0, 0.0, 0.0, 0.0 ).xyz;
	nodeVar0 = ( vec4<f32>( indirectDiffuse, 1.0 ) + vec4<f32>( 1.0, 1.0, 1.0, 0.0 ) );
	indirectDiffuse = nodeVar0.xyz;
	ambientOcclusion = 1.0;
	nodeVar1 = ( indirectDiffuse * vec3<f32>( ambientOcclusion ) );
	indirectDiffuse = nodeVar1;
	nodeVar2 = ( indirectDiffuse * DiffuseColor.xyz );
	indirectDiffuse = nodeVar2;
	directDiffuse = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar3 = ( directDiffuse + indirectDiffuse );
	totalDiffuse = nodeVar3;
	directSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	indirectSpecular = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar4 = ( directSpecular + indirectSpecular );
	totalSpecular = nodeVar4;
	nodeVar5 = ( totalDiffuse + totalSpecular );
	outgoingLight = nodeVar5;
	nodeVar6 = max( vec4<f32>( outgoingLight, DiffuseColor.w ), vec4<f32>( 0.0 ) );
	Output = nodeVar6;
	// result
	output.color = nodeVar6;
	return output;
}
