// Generated by three.js r186 (Node System) for webgpu_tsl_vfx_linkedparticles.
// directives
// system
var<private> instanceIndex : u32;
// locals
// structs
// uniforms
struct NodeBuffer_1018Struct {
	value : array< vec4<f32> >
};
@binding( 0 ) @group( 0 )
var<storage, read_write> NodeBuffer_1018 : NodeBuffer_1018Struct;
struct NodeBuffer_1019Struct {
	value : array< vec4<f32> >
};
@binding( 2 ) @group( 0 )
var<storage, read_write> NodeBuffer_1019 : NodeBuffer_1019Struct;
struct objectStruct {
	nodeUniform1 : f32,
	nodeUniform2 : vec3<f32>,
	nodeUniform3 : vec3<f32>,
	nodeUniform4 : f32,
	nodeUniform6 : u32
};
@binding( 1 ) @group( 0 )
var<uniform> object : objectStruct;
// vars
var<private> nodeVar0 : u32;
var<private> nodeVar1 : u32;
var<private> nodeVar2 : f32;
var<private> nodeVar3 : u32;
var<private> nodeVar4 : u32;
var<private> nodeVar5 : f32;
var<private> nodeVar6 : vec3<f32>;
var<private> nodeVar7 : vec3<f32>;
var<private> nodeVar8 : vec3<f32>;
// codes
fn tsl_mod_float( x : f32, y : f32 ) -> f32 { return x - y * floor( x / y ); }
@compute @workgroup_size( 64, 1, 1 )
fn main( @builtin( global_invocation_id ) globalId : vec3<u32>,
	@builtin( workgroup_id ) workgroupId : vec3<u32>,
	@builtin( local_invocation_id ) localId : vec3<u32>,
	@builtin( num_workgroups ) numWorkgroups : vec3<u32> ) {
	// local vars
	// system
	instanceIndex = globalId.x
		+ globalId.y * ( 64 * numWorkgroups.x )
		+ globalId.z * ( 64 * numWorkgroups.x ) * ( 1 * numWorkgroups.y );
	// flow
	// code
	// flow -> Spawn Particles
	if ( instanceIndex >= object.nodeUniform6 ) { return; }
	NodeBuffer_1018.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].w = 1.0;
	nodeVar0 = ( ( u32( i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ) * 747796405u ) + 2891336453u );
	nodeVar1 = ( ( ( nodeVar0 >> ( ( nodeVar0 >> 28u ) + 4u ) ) ^ nodeVar0 ) * 277803737u );
	nodeVar2 = ( ( f32( ( ( nodeVar1 >> 22u ) ^ nodeVar1 ) ) * 2.3283064365386963e-10 ) * 6.283185307179586 );
	nodeVar3 = ( ( u32( ( i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) + 1 ) ) * 747796405u ) + 2891336453u );
	nodeVar4 = ( ( ( nodeVar3 >> ( ( nodeVar3 >> 28u ) + 4u ) ) ^ nodeVar3 ) * 277803737u );
	nodeVar5 = ( ( f32( ( ( nodeVar4 >> 22u ) ^ nodeVar4 ) ) * 2.3283064365386963e-10 ) * 3.141592653589793 );
	nodeVar6 = vec3<f32>( ( sin( nodeVar2 ) * cos( nodeVar5 ) ), ( sin( nodeVar2 ) * sin( nodeVar5 ) ), cos( nodeVar2 ) );
	nodeVar7 = ( mix( object.nodeUniform2, object.nodeUniform3, clamp( ( f32( instanceIndex ) / ( object.nodeUniform4 - 1.0 ) ), 0.0, 1.0 ) ) + ( nodeVar6 * vec3<f32>( 0.01 ) ) );
	NodeBuffer_1018.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].x = nodeVar7[ 0 ];
	NodeBuffer_1018.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].y = nodeVar7[ 1 ];
	NodeBuffer_1018.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].z = nodeVar7[ 2 ];
	nodeVar8 = ( nodeVar6 * vec3<f32>( 5.0 ) );
	NodeBuffer_1019.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].x = nodeVar8[ 0 ];
	NodeBuffer_1019.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].y = nodeVar8[ 1 ];
	NodeBuffer_1019.value[ i32( tsl_mod_float( ( object.nodeUniform1 + f32( instanceIndex ) ), 8192.0 ) ) ].z = nodeVar8[ 2 ];
}
