// Generated by three.js r186 (Node System) for webgpu_tsl_vfx_linkedparticles.
// global
diagnostic( off, derivative_uniformity );
// structs
struct OutputStruct {
	@location( 0 ) color: vec4<f32>
};
var<private> output : OutputStruct;
// uniforms
struct objectStruct {
	nodeUniform5 : f32,
	nodeUniform6 : f32,
	nodeUniform10 : mat4x4<f32>,
	nodeUniform12 : f32
};
@binding( 0 ) @group( 1 )
var<uniform> object : objectStruct;
struct renderStruct {
	nodeUniform7 : f32,
	cameraProjectionMatrix : mat4x4<f32>,
	cameraViewMatrix : mat4x4<f32>
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
// vars
var<private> DiffuseColor : vec4<f32>;
var<private> nodeVar1 : f32;
var<private> nodeVar2 : f32;
var<private> nodeVar3 : u32;
var<private> nodeVar4 : u32;
var<private> nodeVar5 : f32;
var<private> nodeVar6 : f32;
var<private> Output : vec4<f32>;
var<private> nodeVar7 : vec4<f32>;
// codes
fn mx_floor ( x : f32 ) -> i32 {
	var nodeVar0 : f32;
	nodeVar0 = x;
	return i32( floor( nodeVar0 ) );
}
fn mx_fade ( t : f32 ) -> f32 {
	var nodeVar0 : f32;
	nodeVar0 = t;
	return ( ( ( nodeVar0 * nodeVar0 ) * nodeVar0 ) * ( ( nodeVar0 * ( ( nodeVar0 * 6.0 ) - 15.0 ) ) + 10.0 ) );
}
fn mx_rotl32 ( x : u32, k : i32 ) -> u32 {
	var nodeVar0 : i32;
	var nodeVar1 : u32;
	nodeVar0 = k;
	nodeVar1 = x;
	return ( ( nodeVar1 << u32( nodeVar0 ) ) | ( nodeVar1 >> u32( ( 32 - nodeVar0 ) ) ) );
}
fn mx_bjfinal ( a : u32, b : u32, c : u32 ) -> u32 {
	var nodeVar0 : u32;
	var nodeVar1 : u32;
	var nodeVar2 : u32;
	nodeVar0 = c;
	nodeVar1 = b;
	nodeVar2 = a;
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 14 ) );
	nodeVar2 = ( nodeVar2 ^ nodeVar0 );
	nodeVar2 = ( nodeVar2 - mx_rotl32( nodeVar0, 11 ) );
	nodeVar1 = ( nodeVar1 ^ nodeVar2 );
	nodeVar1 = ( nodeVar1 - mx_rotl32( nodeVar2, 25 ) );
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 16 ) );
	nodeVar2 = ( nodeVar2 ^ nodeVar0 );
	nodeVar2 = ( nodeVar2 - mx_rotl32( nodeVar0, 4 ) );
	nodeVar1 = ( nodeVar1 ^ nodeVar2 );
	nodeVar1 = ( nodeVar1 - mx_rotl32( nodeVar2, 14 ) );
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 24 ) );
	return nodeVar0;
}
fn mx_hash_int_2 ( x : i32, y : i32, z : i32 ) -> u32 {
	var nodeVar0 : i32;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : u32;
	var nodeVar4 : u32;
	var nodeVar5 : u32;
	var nodeVar6 : u32;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = 3u;
	nodeVar4 = 0u;
	nodeVar5 = 0u;
	nodeVar6 = 0u;
	nodeVar6 = ( ( 3735928559u + ( nodeVar3 << 2u ) ) + 13u );
	nodeVar5 = nodeVar6;
	nodeVar4 = nodeVar5;
	nodeVar4 = ( nodeVar4 + u32( nodeVar2 ) );
	nodeVar5 = ( nodeVar5 + u32( nodeVar1 ) );
	nodeVar6 = ( nodeVar6 + u32( nodeVar0 ) );
	return mx_bjfinal( nodeVar4, nodeVar5, nodeVar6 );
}
fn mx_select ( b : bool, t : f32, f : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : bool;
	var nodeVar3 : f32;
	nodeVar0 = f;
	nodeVar1 = t;
	nodeVar2 = b;
	return select( nodeVar0, nodeVar1, nodeVar2 );
}
fn mx_negate_if ( val : f32, b : bool ) -> f32 {
	var nodeVar0 : bool;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	nodeVar0 = b;
	nodeVar1 = val;
	return select( nodeVar1, ( - nodeVar1 ), nodeVar0 );
}
fn mx_gradient_float_1 ( hash : u32, x : f32, y : f32, z : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : u32;
	var nodeVar4 : u32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = hash;
	nodeVar4 = ( nodeVar3 & 15u );
	nodeVar5 = mx_select( ( nodeVar4 < 8u ), nodeVar2, nodeVar1 );
	nodeVar6 = mx_select( ( nodeVar4 < 4u ), nodeVar1, mx_select( ( ( nodeVar4 == 12u ) || ( nodeVar4 == 14u ) ), nodeVar2, nodeVar0 ) );
	return ( mx_negate_if( nodeVar5, bool( ( nodeVar4 & 1u ) ) ) + mx_negate_if( nodeVar6, bool( ( nodeVar4 & 2u ) ) ) );
}
fn mx_trilerp_0 ( v0 : f32, v1 : f32, v2 : f32, v3 : f32, v4 : f32, v5 : f32, v6 : f32, v7 : f32, s : f32, t : f32, r : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : f32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	var nodeVar7 : f32;
	var nodeVar8 : f32;
	var nodeVar9 : f32;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	nodeVar0 = r;
	nodeVar1 = t;
	nodeVar2 = s;
	nodeVar3 = v7;
	nodeVar4 = v6;
	nodeVar5 = v5;
	nodeVar6 = v4;
	nodeVar7 = v3;
	nodeVar8 = v2;
	nodeVar9 = v1;
	nodeVar10 = v0;
	nodeVar11 = ( 1.0 - nodeVar2 );
	nodeVar12 = ( 1.0 - nodeVar1 );
	nodeVar13 = ( 1.0 - nodeVar0 );
	return ( ( nodeVar13 * ( ( nodeVar12 * ( ( nodeVar10 * nodeVar11 ) + ( nodeVar9 * nodeVar2 ) ) ) + ( nodeVar1 * ( ( nodeVar8 * nodeVar11 ) + ( nodeVar7 * nodeVar2 ) ) ) ) ) + ( nodeVar0 * ( ( nodeVar12 * ( ( nodeVar6 * nodeVar11 ) + ( nodeVar5 * nodeVar2 ) ) ) + ( nodeVar1 * ( ( nodeVar4 * nodeVar11 ) + ( nodeVar3 * nodeVar2 ) ) ) ) ) );
}
fn mx_gradient_scale3d_0 ( v : f32 ) -> f32 {
	var nodeVar0 : f32;
	nodeVar0 = v;
	return ( 0.982 * nodeVar0 );
}
fn mx_perlin_noise_float_1 ( p : vec3<f32> ) -> f32 {
	var nodeVar0 : vec3<f32>;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : i32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	var nodeVar7 : f32;
	var nodeVar8 : f32;
	var nodeVar9 : f32;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	nodeVar0 = p;
	nodeVar1 = 0;
	nodeVar2 = 0;
	nodeVar3 = 0;
	nodeVar4 = nodeVar0.x;
	nodeVar1 = mx_floor( nodeVar4 );
	nodeVar5 = ( nodeVar4 - f32( nodeVar1 ) );
	nodeVar6 = nodeVar0.y;
	nodeVar2 = mx_floor( nodeVar6 );
	nodeVar7 = ( nodeVar6 - f32( nodeVar2 ) );
	nodeVar8 = nodeVar0.z;
	nodeVar3 = mx_floor( nodeVar8 );
	nodeVar9 = ( nodeVar8 - f32( nodeVar3 ) );
	nodeVar10 = mx_fade( nodeVar5 );
	nodeVar11 = mx_fade( nodeVar7 );
	nodeVar12 = mx_fade( nodeVar9 );
	nodeVar13 = mx_trilerp_0( mx_gradient_float_1( mx_hash_int_2( nodeVar1, nodeVar2, nodeVar3 ), nodeVar5, nodeVar7, nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), nodeVar2, nodeVar3 ), ( nodeVar5 - 1.0 ), nodeVar7, nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, ( nodeVar2 + 1 ), nodeVar3 ), nodeVar5, ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), nodeVar3 ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, nodeVar2, ( nodeVar3 + 1 ) ), nodeVar5, nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), nodeVar2, ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), nodeVar5, ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), nodeVar10, nodeVar11, nodeVar12 );
	return mx_gradient_scale3d_0( nodeVar13 );
}
fn mx_fractal_noise_float ( p : vec3<f32>, octaves : i32, lacunarity : f32, diminish : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : vec3<f32>;
	var nodeVar3 : f32;
	var nodeVar4 : f32;
	var nodeVar5 : i32;
	nodeVar0 = diminish;
	nodeVar1 = lacunarity;
	nodeVar2 = p;
	nodeVar3 = 0.0;
	nodeVar4 = 1.0;
	nodeVar5 = octaves;
	for ( var i : i32 = 0; i < nodeVar5; i ++ ) {
		nodeVar3 = ( nodeVar3 + ( nodeVar4 * mx_perlin_noise_float_1( nodeVar2 ) ) );
		nodeVar4 = ( nodeVar4 * nodeVar0 );
		nodeVar2 = ( nodeVar2 * vec3<f32>( nodeVar1 ) );
	}
	return nodeVar3;
}
@fragment
fn main( @location( 0 ) @interpolate(flat, either) nodeVarying4 : u32,
	@location( 1 ) nodeVarying5 : vec4<f32>,
	@location( 2 ) nodeVarying6 : vec2<f32> ) -> OutputStruct {
	// flow
	// code
	nodeVar1 = ( object.nodeUniform5 + ( mx_fractal_noise_float( vec3<f32>( ( f32( nodeVarying4 ) * 0.1 ) ), 2, 2.0, 0.5 ) * object.nodeUniform6 ) );
	nodeVar2 = cos( nodeVar1 );
	nodeVar3 = ( ( nodeVarying4 * 747796405u ) + 2891336453u );
	nodeVar4 = ( ( ( nodeVar3 >> ( ( nodeVar3 >> 28u ) + 4u ) ) ^ nodeVar3 ) * 277803737u );
	nodeVar5 = ( ( sin( ( ( ( f32( ( ( nodeVar4 >> 22u ) ^ nodeVar4 ) ) * 2.3283064365386963e-10 ) * 6.283185307179586 ) + ( ( render.nodeUniform7 * 0.5 ) * 6.283185307179586 ) ) ) * 0.5 ) + 0.5 );
	nodeVar6 = ( 1.0 - nodeVarying5.w );
	DiffuseColor = vec4<f32>( ( max( ( ( vec3<f32>( 0.0, 0.0, 1.0 ) * vec3<f32>( nodeVar2 ) ) + ( ( cross( vec3<f32>( 0.57735, 0.57735, 0.57735 ), vec3<f32>( 0.0, 0.0, 1.0 ) ) * vec3<f32>( sin( nodeVar1 ) ) ) + ( vec3<f32>( 0.57735, 0.57735, 0.57735 ) * vec3<f32>( ( dot( vec3<f32>( 0.57735, 0.57735, 0.57735 ), vec3<f32>( 0.0, 0.0, 1.0 ) ) * ( 1.0 - nodeVar2 ) ) ) ) ) ), vec3<f32>( 0.0 ) ) * vec3<f32>( ( ( ( pow( ( pow( nodeVar5, 0.25 ) / ( pow( nodeVar5, 0.25 ) + pow( ( 1.0 - nodeVar5 ), 0.25 ) ) ), ( 1.0 / 0.25 ) ) * 10.0 ) + 1.0 ) * pow( ( pow( nodeVar6, 8.0 ) / ( pow( nodeVar6, 8.0 ) + pow( ( 1.0 - nodeVar6 ), 1.0 ) ) ), ( 1.0 / 8.0 ) ) ) ) ), 1.0 );
	DiffuseColor.w = ( DiffuseColor.w * ( step( length( ( nodeVarying6 - vec2<f32>( 0.5 ) ) ), 0.5 ) * nodeVarying5.w ) );
	nodeVar7 = max( vec4<f32>( DiffuseColor.xyz, DiffuseColor.w ), vec4<f32>( 0.0 ) );
	Output = nodeVar7;
	// result
	output.color = nodeVar7;
	return output;
}
