// Generated by three.js r186 (Node System) for webgpu_tsl_vfx_linkedparticles.
// directives
// system
var<private> instanceIndex : u32;
// locals
// structs
// uniforms
struct NodeBuffer_1018Struct {
	value : array< vec4<f32> >
};
@binding( 0 ) @group( 1 )
var<storage, read_write> NodeBuffer_1018 : NodeBuffer_1018Struct;
struct NodeBuffer_1019Struct {
	value : array< vec4<f32> >
};
@binding( 1 ) @group( 1 )
var<storage, read_write> NodeBuffer_1019 : NodeBuffer_1019Struct;
struct NodeBuffer_1171Struct {
	value : array< vec4<f32> >
};
@binding( 3 ) @group( 1 )
var<storage, read_write> NodeBuffer_1171 : NodeBuffer_1171Struct;
struct NodeBuffer_1172Struct {
	value : array< vec4<f32> >
};
@binding( 4 ) @group( 1 )
var<storage, read_write> NodeBuffer_1172 : NodeBuffer_1172Struct;
struct objectStruct {
	nodeUniform2 : f32,
	nodeUniform3 : f32,
	nodeUniform4 : f32,
	nodeUniform5 : f32,
	nodeUniform6 : f32,
	nodeUniform7 : f32,
	nodeUniform9 : f32,
	nodeUniform10 : f32,
	nodeUniform12 : f32,
	nodeUniform14 : f32,
	nodeUniform15 : f32,
	nodeUniform16 : u32
};
@binding( 2 ) @group( 1 )
var<uniform> object : objectStruct;
struct renderStruct {
	nodeUniform8 : f32
};
@binding( 0 ) @group( 0 )
var<uniform> render : renderStruct;
// vars
var<private> nodeVar0 : vec3<f32>;
var<private> nodeVar1 : vec3<f32>;
var<private> nodeVar2 : f32;
var<private> nodeVar3 : vec3<f32>;
var<private> nodeVar4 : f32;
var<private> nodeVar5 : vec3<f32>;
var<private> nodeVar6 : f32;
var<private> nodeVar7 : f32;
var<private> nodeVar8 : vec3<f32>;
var<private> nodeVar9 : f32;
var<private> nodeVar10 : vec3<f32>;
var<private> nodeVar11 : f32;
var<private> nodeVar12 : bool;
var<private> nodeVar13 : u32;
var<private> nodeVar14 : vec3<f32>;
var<private> nodeVar15 : vec3<f32>;
var<private> nodeVar16 : vec3<f32>;
var<private> nodeVar17 : vec3<f32>;
var<private> nodeVar18 : u32;
var<private> nodeVar19 : vec3<f32>;
var<private> nodeVar20 : vec3<f32>;
var<private> nodeVar21 : vec3<f32>;
var<private> nodeVar22 : vec3<f32>;
var<private> nodeVar23 : f32;
var<private> nodeVar24 : f32;
var<private> nodeVar25 : vec3<f32>;
var<private> nodeVar26 : vec3<f32>;
var<private> nodeVar27 : vec3<f32>;
// codes
fn mx_rotl32 ( x : u32, k : i32 ) -> u32 {
	var nodeVar0 : i32;
	var nodeVar1 : u32;
	nodeVar0 = k;
	nodeVar1 = x;
	return ( ( nodeVar1 << u32( nodeVar0 ) ) | ( nodeVar1 >> u32( ( 32 - nodeVar0 ) ) ) );
}
fn mx_bjfinal ( a : u32, b : u32, c : u32 ) -> u32 {
	var nodeVar0 : u32;
	var nodeVar1 : u32;
	var nodeVar2 : u32;
	nodeVar0 = c;
	nodeVar1 = b;
	nodeVar2 = a;
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 14 ) );
	nodeVar2 = ( nodeVar2 ^ nodeVar0 );
	nodeVar2 = ( nodeVar2 - mx_rotl32( nodeVar0, 11 ) );
	nodeVar1 = ( nodeVar1 ^ nodeVar2 );
	nodeVar1 = ( nodeVar1 - mx_rotl32( nodeVar2, 25 ) );
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 16 ) );
	nodeVar2 = ( nodeVar2 ^ nodeVar0 );
	nodeVar2 = ( nodeVar2 - mx_rotl32( nodeVar0, 4 ) );
	nodeVar1 = ( nodeVar1 ^ nodeVar2 );
	nodeVar1 = ( nodeVar1 - mx_rotl32( nodeVar2, 14 ) );
	nodeVar0 = ( nodeVar0 ^ nodeVar1 );
	nodeVar0 = ( nodeVar0 - mx_rotl32( nodeVar1, 24 ) );
	return nodeVar0;
}
fn mx_hash_int_2 ( x : i32, y : i32, z : i32 ) -> u32 {
	var nodeVar0 : i32;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : u32;
	var nodeVar4 : u32;
	var nodeVar5 : u32;
	var nodeVar6 : u32;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = 3u;
	nodeVar4 = 0u;
	nodeVar5 = 0u;
	nodeVar6 = 0u;
	nodeVar6 = ( ( 3735928559u + ( nodeVar3 << 2u ) ) + 13u );
	nodeVar5 = nodeVar6;
	nodeVar4 = nodeVar5;
	nodeVar4 = ( nodeVar4 + u32( nodeVar2 ) );
	nodeVar5 = ( nodeVar5 + u32( nodeVar1 ) );
	nodeVar6 = ( nodeVar6 + u32( nodeVar0 ) );
	return mx_bjfinal( nodeVar4, nodeVar5, nodeVar6 );
}
fn mx_select ( b : bool, t : f32, f : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : bool;
	var nodeVar3 : f32;
	nodeVar0 = f;
	nodeVar1 = t;
	nodeVar2 = b;
	return select( nodeVar0, nodeVar1, nodeVar2 );
}
fn mx_negate_if ( val : f32, b : bool ) -> f32 {
	var nodeVar0 : bool;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	nodeVar0 = b;
	nodeVar1 = val;
	return select( nodeVar1, ( - nodeVar1 ), nodeVar0 );
}
fn mx_gradient_float_1 ( hash : u32, x : f32, y : f32, z : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : u32;
	var nodeVar4 : u32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = hash;
	nodeVar4 = ( nodeVar3 & 15u );
	nodeVar5 = mx_select( ( nodeVar4 < 8u ), nodeVar2, nodeVar1 );
	nodeVar6 = mx_select( ( nodeVar4 < 4u ), nodeVar1, mx_select( ( ( nodeVar4 == 12u ) || ( nodeVar4 == 14u ) ), nodeVar2, nodeVar0 ) );
	return ( mx_negate_if( nodeVar5, bool( ( nodeVar4 & 1u ) ) ) + mx_negate_if( nodeVar6, bool( ( nodeVar4 & 2u ) ) ) );
}
fn mx_floor ( x : f32 ) -> i32 {
	var nodeVar0 : f32;
	nodeVar0 = x;
	return i32( floor( nodeVar0 ) );
}
fn mx_fade ( t : f32 ) -> f32 {
	var nodeVar0 : f32;
	nodeVar0 = t;
	return ( ( ( nodeVar0 * nodeVar0 ) * nodeVar0 ) * ( ( nodeVar0 * ( ( nodeVar0 * 6.0 ) - 15.0 ) ) + 10.0 ) );
}
fn mx_hash_vec3_1 ( x : i32, y : i32, z : i32 ) -> vec3<u32> {
	var nodeVar0 : i32;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : u32;
	var nodeVar4 : vec3<u32>;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = mx_hash_int_2( nodeVar2, nodeVar1, nodeVar0 );
	nodeVar4 = vec3<u32>( 0u, 0u, 0u );
	nodeVar4.x = ( nodeVar3 & 255u );
	nodeVar4.y = ( ( nodeVar3 >> 8u ) & 255u );
	nodeVar4.z = ( ( nodeVar3 >> 16u ) & 255u );
	return nodeVar4;
}
fn mx_gradient_vec3_1 ( hash : vec3<u32>, x : f32, y : f32, z : f32 ) -> vec3<f32> {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : vec3<u32>;
	nodeVar0 = z;
	nodeVar1 = y;
	nodeVar2 = x;
	nodeVar3 = hash;
	return vec3<f32>( mx_gradient_float_1( nodeVar3.x, nodeVar2, nodeVar1, nodeVar0 ), mx_gradient_float_1( nodeVar3.y, nodeVar2, nodeVar1, nodeVar0 ), mx_gradient_float_1( nodeVar3.z, nodeVar2, nodeVar1, nodeVar0 ) );
}
fn mx_trilerp_1 ( v0 : vec3<f32>, v1 : vec3<f32>, v2 : vec3<f32>, v3 : vec3<f32>, v4 : vec3<f32>, v5 : vec3<f32>, v6 : vec3<f32>, v7 : vec3<f32>, s : f32, t : f32, r : f32 ) -> vec3<f32> {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : vec3<f32>;
	var nodeVar4 : vec3<f32>;
	var nodeVar5 : vec3<f32>;
	var nodeVar6 : vec3<f32>;
	var nodeVar7 : vec3<f32>;
	var nodeVar8 : vec3<f32>;
	var nodeVar9 : vec3<f32>;
	var nodeVar10 : vec3<f32>;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	nodeVar0 = r;
	nodeVar1 = t;
	nodeVar2 = s;
	nodeVar3 = v7;
	nodeVar4 = v6;
	nodeVar5 = v5;
	nodeVar6 = v4;
	nodeVar7 = v3;
	nodeVar8 = v2;
	nodeVar9 = v1;
	nodeVar10 = v0;
	nodeVar11 = ( 1.0 - nodeVar2 );
	nodeVar12 = ( 1.0 - nodeVar1 );
	nodeVar13 = ( 1.0 - nodeVar0 );
	return ( ( vec3<f32>( nodeVar13 ) * ( ( vec3<f32>( nodeVar12 ) * ( ( nodeVar10 * vec3<f32>( nodeVar11 ) ) + ( nodeVar9 * vec3<f32>( nodeVar2 ) ) ) ) + ( vec3<f32>( nodeVar1 ) * ( ( nodeVar8 * vec3<f32>( nodeVar11 ) ) + ( nodeVar7 * vec3<f32>( nodeVar2 ) ) ) ) ) ) + ( vec3<f32>( nodeVar0 ) * ( ( vec3<f32>( nodeVar12 ) * ( ( nodeVar6 * vec3<f32>( nodeVar11 ) ) + ( nodeVar5 * vec3<f32>( nodeVar2 ) ) ) ) + ( vec3<f32>( nodeVar1 ) * ( ( nodeVar4 * vec3<f32>( nodeVar11 ) ) + ( nodeVar3 * vec3<f32>( nodeVar2 ) ) ) ) ) ) );
}
fn mx_gradient_scale3d_1 ( v : vec3<f32> ) -> vec3<f32> {
	var nodeVar0 : vec3<f32>;
	nodeVar0 = v;
	return ( vec3<f32>( 0.982 ) * nodeVar0 );
}
fn mx_perlin_noise_vec3_1 ( p : vec3<f32> ) -> vec3<f32> {
	var nodeVar0 : vec3<f32>;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : i32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	var nodeVar7 : f32;
	var nodeVar8 : f32;
	var nodeVar9 : f32;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : vec3<f32>;
	nodeVar0 = p;
	nodeVar1 = 0;
	nodeVar2 = 0;
	nodeVar3 = 0;
	nodeVar4 = nodeVar0.x;
	nodeVar1 = mx_floor( nodeVar4 );
	nodeVar5 = ( nodeVar4 - f32( nodeVar1 ) );
	nodeVar6 = nodeVar0.y;
	nodeVar2 = mx_floor( nodeVar6 );
	nodeVar7 = ( nodeVar6 - f32( nodeVar2 ) );
	nodeVar8 = nodeVar0.z;
	nodeVar3 = mx_floor( nodeVar8 );
	nodeVar9 = ( nodeVar8 - f32( nodeVar3 ) );
	nodeVar10 = mx_fade( nodeVar5 );
	nodeVar11 = mx_fade( nodeVar7 );
	nodeVar12 = mx_fade( nodeVar9 );
	nodeVar13 = mx_trilerp_1( mx_gradient_vec3_1( mx_hash_vec3_1( nodeVar1, nodeVar2, nodeVar3 ), nodeVar5, nodeVar7, nodeVar9 ), mx_gradient_vec3_1( mx_hash_vec3_1( ( nodeVar1 + 1 ), nodeVar2, nodeVar3 ), ( nodeVar5 - 1.0 ), nodeVar7, nodeVar9 ), mx_gradient_vec3_1( mx_hash_vec3_1( nodeVar1, ( nodeVar2 + 1 ), nodeVar3 ), nodeVar5, ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_vec3_1( mx_hash_vec3_1( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), nodeVar3 ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_vec3_1( mx_hash_vec3_1( nodeVar1, nodeVar2, ( nodeVar3 + 1 ) ), nodeVar5, nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_vec3_1( mx_hash_vec3_1( ( nodeVar1 + 1 ), nodeVar2, ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_vec3_1( mx_hash_vec3_1( nodeVar1, ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), nodeVar5, ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), mx_gradient_vec3_1( mx_hash_vec3_1( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), nodeVar10, nodeVar11, nodeVar12 );
	return mx_gradient_scale3d_1( nodeVar13 );
}
fn mx_trilerp_0 ( v0 : f32, v1 : f32, v2 : f32, v3 : f32, v4 : f32, v5 : f32, v6 : f32, v7 : f32, s : f32, t : f32, r : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : f32;
	var nodeVar3 : f32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	var nodeVar7 : f32;
	var nodeVar8 : f32;
	var nodeVar9 : f32;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	nodeVar0 = r;
	nodeVar1 = t;
	nodeVar2 = s;
	nodeVar3 = v7;
	nodeVar4 = v6;
	nodeVar5 = v5;
	nodeVar6 = v4;
	nodeVar7 = v3;
	nodeVar8 = v2;
	nodeVar9 = v1;
	nodeVar10 = v0;
	nodeVar11 = ( 1.0 - nodeVar2 );
	nodeVar12 = ( 1.0 - nodeVar1 );
	nodeVar13 = ( 1.0 - nodeVar0 );
	return ( ( nodeVar13 * ( ( nodeVar12 * ( ( nodeVar10 * nodeVar11 ) + ( nodeVar9 * nodeVar2 ) ) ) + ( nodeVar1 * ( ( nodeVar8 * nodeVar11 ) + ( nodeVar7 * nodeVar2 ) ) ) ) ) + ( nodeVar0 * ( ( nodeVar12 * ( ( nodeVar6 * nodeVar11 ) + ( nodeVar5 * nodeVar2 ) ) ) + ( nodeVar1 * ( ( nodeVar4 * nodeVar11 ) + ( nodeVar3 * nodeVar2 ) ) ) ) ) );
}
fn mx_gradient_scale3d_0 ( v : f32 ) -> f32 {
	var nodeVar0 : f32;
	nodeVar0 = v;
	return ( 0.982 * nodeVar0 );
}
fn mx_perlin_noise_float_1 ( p : vec3<f32> ) -> f32 {
	var nodeVar0 : vec3<f32>;
	var nodeVar1 : i32;
	var nodeVar2 : i32;
	var nodeVar3 : i32;
	var nodeVar4 : f32;
	var nodeVar5 : f32;
	var nodeVar6 : f32;
	var nodeVar7 : f32;
	var nodeVar8 : f32;
	var nodeVar9 : f32;
	var nodeVar10 : f32;
	var nodeVar11 : f32;
	var nodeVar12 : f32;
	var nodeVar13 : f32;
	nodeVar0 = p;
	nodeVar1 = 0;
	nodeVar2 = 0;
	nodeVar3 = 0;
	nodeVar4 = nodeVar0.x;
	nodeVar1 = mx_floor( nodeVar4 );
	nodeVar5 = ( nodeVar4 - f32( nodeVar1 ) );
	nodeVar6 = nodeVar0.y;
	nodeVar2 = mx_floor( nodeVar6 );
	nodeVar7 = ( nodeVar6 - f32( nodeVar2 ) );
	nodeVar8 = nodeVar0.z;
	nodeVar3 = mx_floor( nodeVar8 );
	nodeVar9 = ( nodeVar8 - f32( nodeVar3 ) );
	nodeVar10 = mx_fade( nodeVar5 );
	nodeVar11 = mx_fade( nodeVar7 );
	nodeVar12 = mx_fade( nodeVar9 );
	nodeVar13 = mx_trilerp_0( mx_gradient_float_1( mx_hash_int_2( nodeVar1, nodeVar2, nodeVar3 ), nodeVar5, nodeVar7, nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), nodeVar2, nodeVar3 ), ( nodeVar5 - 1.0 ), nodeVar7, nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, ( nodeVar2 + 1 ), nodeVar3 ), nodeVar5, ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), nodeVar3 ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), nodeVar9 ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, nodeVar2, ( nodeVar3 + 1 ) ), nodeVar5, nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), nodeVar2, ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), nodeVar7, ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( nodeVar1, ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), nodeVar5, ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), mx_gradient_float_1( mx_hash_int_2( ( nodeVar1 + 1 ), ( nodeVar2 + 1 ), ( nodeVar3 + 1 ) ), ( nodeVar5 - 1.0 ), ( nodeVar7 - 1.0 ), ( nodeVar9 - 1.0 ) ), nodeVar10, nodeVar11, nodeVar12 );
	return mx_gradient_scale3d_0( nodeVar13 );
}
fn mx_fractal_noise_vec3 ( p : vec3<f32>, octaves : i32, lacunarity : f32, diminish : f32 ) -> vec3<f32> {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : vec3<f32>;
	var nodeVar3 : vec3<f32>;
	var nodeVar4 : f32;
	var nodeVar5 : i32;
	nodeVar0 = diminish;
	nodeVar1 = lacunarity;
	nodeVar2 = p;
	nodeVar3 = vec3<f32>( 0.0, 0.0, 0.0 );
	nodeVar4 = 1.0;
	nodeVar5 = octaves;
	for ( var i : i32 = 0; i < nodeVar5; i ++ ) {
		nodeVar3 = ( nodeVar3 + ( vec3<f32>( nodeVar4 ) * mx_perlin_noise_vec3_1( nodeVar2 ) ) );
		nodeVar4 = ( nodeVar4 * nodeVar0 );
		nodeVar2 = ( nodeVar2 * vec3<f32>( nodeVar1 ) );
	}
	return nodeVar3;
}
fn mx_fractal_noise_float ( p : vec3<f32>, octaves : i32, lacunarity : f32, diminish : f32 ) -> f32 {
	var nodeVar0 : f32;
	var nodeVar1 : f32;
	var nodeVar2 : vec3<f32>;
	var nodeVar3 : f32;
	var nodeVar4 : f32;
	var nodeVar5 : i32;
	nodeVar0 = diminish;
	nodeVar1 = lacunarity;
	nodeVar2 = p;
	nodeVar3 = 0.0;
	nodeVar4 = 1.0;
	nodeVar5 = octaves;
	for ( var i : i32 = 0; i < nodeVar5; i ++ ) {
		nodeVar3 = ( nodeVar3 + ( nodeVar4 * mx_perlin_noise_float_1( nodeVar2 ) ) );
		nodeVar4 = ( nodeVar4 * nodeVar0 );
		nodeVar2 = ( nodeVar2 * vec3<f32>( nodeVar1 ) );
	}
	return nodeVar3;
}
@compute @workgroup_size( 64, 1, 1 )
fn main( @builtin( global_invocation_id ) globalId : vec3<u32>,
	@builtin( workgroup_id ) workgroupId : vec3<u32>,
	@builtin( local_invocation_id ) localId : vec3<u32>,
	@builtin( num_workgroups ) numWorkgroups : vec3<u32> ) {
	// local vars
	// system
	instanceIndex = globalId.x
		+ globalId.y * ( 64 * numWorkgroups.x )
		+ globalId.z * ( 64 * numWorkgroups.x ) * ( 1 * numWorkgroups.y );
	// flow
	// code
	// flow -> Update Particles
	if ( instanceIndex >= object.nodeUniform16 ) { return; }
	if ( ( NodeBuffer_1018.value[ instanceIndex ].w > 0.0 ) ) {
		nodeVar0 = ( NodeBuffer_1019.value[ instanceIndex ].xyz + ( ( mx_fractal_noise_vec3( ( NodeBuffer_1018.value[ instanceIndex ].xyz * vec3<f32>( object.nodeUniform2 ) ), i32( object.nodeUniform3 ), object.nodeUniform4, object.nodeUniform5 ) * vec3<f32>( object.nodeUniform6 ) ) * vec3<f32>( ( NodeBuffer_1018.value[ instanceIndex ].w + 0.01 ) ) ) );
		NodeBuffer_1019.value[ instanceIndex ].x = nodeVar0[ 0 ];
		NodeBuffer_1019.value[ instanceIndex ].y = nodeVar0[ 1 ];
		NodeBuffer_1019.value[ instanceIndex ].z = nodeVar0[ 2 ];
		nodeVar1 = ( NodeBuffer_1019.value[ instanceIndex ].xyz * vec3<f32>( ( 1.0 - object.nodeUniform7 ) ) );
		NodeBuffer_1019.value[ instanceIndex ].x = nodeVar1[ 0 ];
		NodeBuffer_1019.value[ instanceIndex ].y = nodeVar1[ 1 ];
		NodeBuffer_1019.value[ instanceIndex ].z = nodeVar1[ 2 ];
		nodeVar2 = ( ( render.nodeUniform8 * 0.1 ) * object.nodeUniform9 );
		nodeVar3 = ( NodeBuffer_1018.value[ instanceIndex ].xyz + ( NodeBuffer_1019.value[ instanceIndex ].xyz * vec3<f32>( nodeVar2 ) ) );
		NodeBuffer_1018.value[ instanceIndex ].x = nodeVar3[ 0 ];
		NodeBuffer_1018.value[ instanceIndex ].y = nodeVar3[ 1 ];
		NodeBuffer_1018.value[ instanceIndex ].z = nodeVar3[ 2 ];
		NodeBuffer_1018.value[ instanceIndex ].w = ( NodeBuffer_1018.value[ instanceIndex ].w - ( nodeVar2 * ( 1.0 / object.nodeUniform10 ) ) );
		nodeVar4 = 10000.0;
		nodeVar5 = vec3<f32>( 0.0, 0.0, 0.0 );
		nodeVar6 = 0.0;
		nodeVar7 = 10000.0;
		nodeVar8 = vec3<f32>( 0.0, 0.0, 0.0 );
		nodeVar9 = 0.0;
		for ( var i : i32 = 0; i < 8192; i ++ ) {
			if ( ( ( f32( i ) != f32( instanceIndex ) ) && ( NodeBuffer_1018.value[ i ].w > 0.0 ) ) ) {
				nodeVar10 = ( NodeBuffer_1018.value[ instanceIndex ].xyz - NodeBuffer_1018.value[ i ].xyz );
				nodeVar11 = dot( nodeVar10, nodeVar10 );
				nodeVar12 = ( nodeVar11 > 0.0 );
				if ( ( ( nodeVar11 < nodeVar4 ) && nodeVar12 ) ) {
					nodeVar4 = nodeVar11;
					nodeVar5 = NodeBuffer_1018.value[ i ].xyz;
					nodeVar6 = NodeBuffer_1018.value[ i ].w;
				} else {
					if ( ( ( nodeVar11 < nodeVar7 ) && nodeVar12 ) ) {
						nodeVar7 = nodeVar11;
						nodeVar8 = NodeBuffer_1018.value[ i ].xyz;
						nodeVar9 = NodeBuffer_1018.value[ i ].w;
					}
				}
			}
		}
		nodeVar13 = ( instanceIndex * 8u );
		nodeVar14 = NodeBuffer_1018.value[ instanceIndex ].xyz;
		NodeBuffer_1171.value[ nodeVar13 ].x = nodeVar14[ 0 ];
		NodeBuffer_1171.value[ nodeVar13 ].y = nodeVar14[ 1 ];
		NodeBuffer_1171.value[ nodeVar13 ].z = nodeVar14[ 2 ];
		NodeBuffer_1171.value[ nodeVar13 ].y = ( NodeBuffer_1171.value[ nodeVar13 ].y + object.nodeUniform12 );
		nodeVar15 = NodeBuffer_1018.value[ instanceIndex ].xyz;
		NodeBuffer_1171.value[ ( nodeVar13 + 1u ) ].x = nodeVar15[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 1u ) ].y = nodeVar15[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 1u ) ].z = nodeVar15[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 1u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar13 + 1u ) ].y + ( - object.nodeUniform12 ) );
		nodeVar16 = nodeVar5;
		NodeBuffer_1171.value[ ( nodeVar13 + 2u ) ].x = nodeVar16[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 2u ) ].y = nodeVar16[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 2u ) ].z = nodeVar16[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 2u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar13 + 2u ) ].y + ( - object.nodeUniform12 ) );
		nodeVar17 = nodeVar5;
		NodeBuffer_1171.value[ ( nodeVar13 + 3u ) ].x = nodeVar17[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 3u ) ].y = nodeVar17[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 3u ) ].z = nodeVar17[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar13 + 3u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar13 + 3u ) ].y + object.nodeUniform12 );
		nodeVar18 = ( nodeVar13 + 4u );
		nodeVar19 = NodeBuffer_1018.value[ instanceIndex ].xyz;
		NodeBuffer_1171.value[ nodeVar18 ].x = nodeVar19[ 0 ];
		NodeBuffer_1171.value[ nodeVar18 ].y = nodeVar19[ 1 ];
		NodeBuffer_1171.value[ nodeVar18 ].z = nodeVar19[ 2 ];
		NodeBuffer_1171.value[ nodeVar18 ].y = ( NodeBuffer_1171.value[ nodeVar18 ].y + object.nodeUniform12 );
		nodeVar20 = NodeBuffer_1018.value[ instanceIndex ].xyz;
		NodeBuffer_1171.value[ ( nodeVar18 + 1u ) ].x = nodeVar20[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 1u ) ].y = nodeVar20[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 1u ) ].z = nodeVar20[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 1u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar18 + 1u ) ].y + ( - object.nodeUniform12 ) );
		nodeVar21 = nodeVar8;
		NodeBuffer_1171.value[ ( nodeVar18 + 2u ) ].x = nodeVar21[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 2u ) ].y = nodeVar21[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 2u ) ].z = nodeVar21[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 2u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar18 + 2u ) ].y + ( - object.nodeUniform12 ) );
		nodeVar22 = nodeVar8;
		NodeBuffer_1171.value[ ( nodeVar18 + 3u ) ].x = nodeVar22[ 0 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 3u ) ].y = nodeVar22[ 1 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 3u ) ].z = nodeVar22[ 2 ];
		NodeBuffer_1171.value[ ( nodeVar18 + 3u ) ].y = ( NodeBuffer_1171.value[ ( nodeVar18 + 3u ) ].y + object.nodeUniform12 );
		for ( var i : i32 = 0; i < 4; i ++ ) {
			nodeVar23 = ( object.nodeUniform14 + ( mx_fractal_noise_float( vec3<f32>( ( f32( instanceIndex ) * 0.1 ) ), 2, 2.0, 0.5 ) * object.nodeUniform15 ) );
			nodeVar24 = cos( nodeVar23 );
			nodeVar25 = max( ( ( vec3<f32>( 0.0, 0.0, 1.0 ) * vec3<f32>( nodeVar24 ) ) + ( ( cross( vec3<f32>( 0.57735, 0.57735, 0.57735 ), vec3<f32>( 0.0, 0.0, 1.0 ) ) * vec3<f32>( sin( nodeVar23 ) ) ) + ( vec3<f32>( 0.57735, 0.57735, 0.57735 ) * vec3<f32>( ( dot( vec3<f32>( 0.57735, 0.57735, 0.57735 ), vec3<f32>( 0.0, 0.0, 1.0 ) ) * ( 1.0 - nodeVar24 ) ) ) ) ) ), vec3<f32>( 0.0 ) );
			nodeVar26 = nodeVar25;
			NodeBuffer_1172.value[ ( nodeVar13 + u32( i ) ) ].x = nodeVar26[ 0 ];
			NodeBuffer_1172.value[ ( nodeVar13 + u32( i ) ) ].y = nodeVar26[ 1 ];
			NodeBuffer_1172.value[ ( nodeVar13 + u32( i ) ) ].z = nodeVar26[ 2 ];
			NodeBuffer_1172.value[ ( nodeVar13 + u32( i ) ) ].w = pow( max( 0.0, min( nodeVar6, NodeBuffer_1018.value[ instanceIndex ].w ) ), 0.8 );
			nodeVar27 = nodeVar25;
			NodeBuffer_1172.value[ ( nodeVar18 + u32( i ) ) ].x = nodeVar27[ 0 ];
			NodeBuffer_1172.value[ ( nodeVar18 + u32( i ) ) ].y = nodeVar27[ 1 ];
			NodeBuffer_1172.value[ ( nodeVar18 + u32( i ) ) ].z = nodeVar27[ 2 ];
			NodeBuffer_1172.value[ ( nodeVar18 + u32( i ) ) ].w = pow( max( 0.0, min( nodeVar9, NodeBuffer_1018.value[ instanceIndex ].w ) ), 0.8 );
		}
	}
}
